### PR TITLE
add exportTable method

### PR DESCRIPTION
**Pull request by rafaeljusi**
just extracted the code into a new method so you can call it with custom button/code

### CODE REVIEW

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show this PR working, thanks!

**Comment by rafaeljusi** [comment]
sorry, i had to fix some details. here is the fiddle: [http://jsfiddle.net/kens3r5x/9/](http://jsfiddle.net/kens3r5x/9/)

**Comment by djhvscf** [comment]
Hi @rafaeljusi that example is not working properly

**Comment by rafaeljusi** [comment]
Hi @djhvscf now the link is correct, i accidentally removed some code on the previous link.

**Pull request merged**
