### PR TITLE
Fix Filter Control overwrite "search" paramater

### LINKED ISSUE #2776: Filter Control overwrites "search" parameter in API call
With both "search" and Filter Control enabled, Filter Control will overwrite the "search" parameter sent to server/API.

Enable search and filterControl
Search for something (not using Filter Control)
Search for something using Filter Control

The last search will now populate both "filter" and "search" parameter sent to API/server. The original search is lost (but still populating the search input field).

### PR DESCRIPTION
**Pull request by Bakke**
Fixes #2776

### CODE REVIEW

**Comment by djhvscf** [comment]
@Bakke do you have any fiddle where we can see the issue and the solution?, thanks.

**Comment by Bakke** [comment]
https://jsfiddle.net/p63sfsvd/5/

Sorry, I have no working API examples right now using HTTPS.

If you search using the "search"-field you get a request like: `https://jsonplaceholder.typicode.com/posts?search=test1&order=asc&offset=0&limit=10`. The "search" parameter is now "test1".

If you then filter a column you get a new request like: `https://jsonplaceholder.typicode.com/posts?search=test2&order=asc&offset=0&limit=10&filter=%7B%22title%22%3A%22test2%22%7D`. The "search" parameter is now "test2" (the same as filter) - the original value is lost.

**Comment by Bakke** [comment]
Working example: https://jsfiddle.net/qbkn7991/10/

If you search for "luke", then filter "Gender"-column to "male" the request will be: `https://swapi.co/api/people/?search=luke&order=asc&offset=0&limit=10&filter=%7B%22gender%22%3A%22male%22%7D`

**Comment by wenzhixin** [comment]
@djhvscf help to review this please.

**Comment by DustinUtecht** [comment]
@djhvscf any update here ?

**Comment by diemus** [comment]
thanks for the solution@Bakke ,I have the same problem,it seems the newest code didn't sovle this problem,

**Comment by mciesiel** [comment]
Thanks for the solution, I have the problem too
As diemus said, the fix is not in the last version, can you resolve conflicts and create a new version? 
Thank you in advance

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this PR. If you want, please create a new **PR** with this change against develop.

**Pull request closed without merging**
