### PR TITLE
Plugin to enable the multiple selection row v2

### PR DESCRIPTION
**Pull request by Bighamster**
Plugin to enable the multiple selection row. You can use the ctrl+click to select one row or use shift+click to select a range of rows.

jsFiddle example: [multiple selection row v2](https://jsfiddle.net/Bighamster/4rw6679x/)

### CODE REVIEW

**Comment by djhvscf** [comment]
This extension looks good but please review my comments

**Comment by djhvscf** [comment]
@wenzhixin what do you think if we merge this extension into [multiple-selection-row](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/multiple-selection-row)

**Comment by djhvscf** [comment]
Any update @Bighamster

**Comment by wenzhixin** [comment]
@djhvscf I agree with you, it's better to merge this extension into multiple-selection-row.

**Comment by djhvscf** [comment]
@wenzhixin, ok merging with existing extension

**Comment by wenzhixin** [comment]
Added `multipleSelectRow` as table option and removed `multiple-selection-row` extension.
ref #4256 https://github.com/wenzhixin/bootstrap-table/pull/4256/commits/4881222a994f7348ea9b0e08dcd110307f89d177

Thanks for your contribution! @Bighamster @djhvscf

**Pull request closed without merging**
