### PR TITLE
[Bugfix] table keeps getting bigger

### PR DESCRIPTION
**Pull request by reatang**
if `<th>` have padding。The table keeps getting bigger。

### CODE REVIEW

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show the changes, thanks!

**Comment by reatang** [comment]
这个功能真心强大呀
仿照[示例](https://examples.bootstrap-table.com/#column-options/footer-formatter.html) 稍作修改： [代码Code](https://live.bootstrap-table.com/code/reatang/296)

**Comment by UtechtDustin** [comment]
@wenzhixin 
Looks good for me, but im not sure if that could break other width calculations.

**Comment by wenzhixin** [comment]
I will test it.

**Comment by wenzhixin** [comment]
Thanks for your contribution!

**Comment by reatang** [comment]
You're welcome. This is what I should do.

**Pull request merged**
