### PR TITLE
Fix initSort(): Avoid additional sorting when server side sort enabled

### PR DESCRIPTION
**Pull request by rame0**

### CODE REVIEW

**Comment by UtechtDustin** [comment]
The main change looks good on the first moment, please fix the CI issues (Execute the pre-commit funktion).

**Comment by rame0** [comment]
#4992

**Comment by UtechtDustin** [comment]
Could you please provide us two examples (before fix and after fix ?) using our [Editor](live.bootstrap-table.com/) ?

**Comment by rame0** [comment]
> Could you please provide us two examples (before fix and after fix ?) using our [Editor](live.bootstrap-table.com/) ?

Sure
### Before
Before


### After
After

**Comment by rame0** [comment]
There is no way (at list I could not find it) to create examples in [Editor](https://live.bootstrap-table.com/).

You can simulate incorrect behavior by adding something trickier than strings and integers in examples data such as dates or status (as strings)(https://examples.wenzhixin.net.cn/examples/bootstrap_table/data). 

When server sorts, lets say, `order status` in particular order it is not always **ASC** or **DESC** order of `order status` ids or names. It could be **priority** of `order status`. 
Server sorts data and returns it in intended order. 
Then bootstrapTable (even if `serverSort = true`) sorts it again and breakes sort order (as shown on screenshots above) because it receives string values and sorts it as strings.

**Comment by rame0** [comment]
Also it is logically incorrect to perform sorting on client when sorting already made by server.

**Comment by UtechtDustin** [comment]
Looks ok for me, what do you think @wenzhixin @djhvscf  ?

**Comment by wenzhixin** [comment]
I think this problem is the same as #4919 and has been fixed in #4940. https://github.com/wenzhixin/bootstrap-table/pull/4940/commits/6a2526d37b7bb1fc148be58f37a7913eb1f29e15

The example for #4992:

1.16.0: https://live.bootstrap-table.com/code/wenzhixin/3316
develop: https://live.bootstrap-table.com/code/wenzhixin/3317

**Comment by wenzhixin** [comment]
Please help verify if there is a problem in the `develop` branch, thank you @rame0 @Shawn8901

**Comment by rame0** [comment]
I'v made my own examples

develop: https://live.bootstrap-table.com/code/rame0/3318
1.16.0: https://live.bootstrap-table.com/code/rame0/3319

Develop branch works just fine. 
I can't check it on prod data (as on screens above), will do after release.
Request can be closed i think.

**Comment by wenzhixin** [comment]
OK, thanks for your contribution!

**Comment by Shawn8901** [comment]
Hi,
sorry for the delay, i was not at home, so not able to reproduce the issue in time.
But i am also confirming, that the issue is fixed on my use case. Thank you very much for the fix.

**Pull request closed without merging**
