### PR TITLE
fix existsOptionInSelectControl

### PR DESCRIPTION
**Pull request by aleko-et**

### CODE REVIEW

**Comment by aleko-et** [comment]
Fix bug with unique values

**Comment by djhvscf** [comment]
Can you share a fiddle with the original bug, please? @aleko-et

**Comment by aleko-et** [comment]
Hello!
Problem was with numeric values from json. 
Here is original version: http://jsfiddle.net/4a89508f/ . Try to select some option in id field.
Trouble was with types. Here is fixed version:
http://jsfiddle.net/pq1mgoaq/1/
No problems with repeating values.

**Comment by djhvscf** [comment]
Ok, You can merge this PR, @wenzhixin

**Comment by wenzhixin** [comment]
Need to update this pull request @aleko-et .

**Comment by aleko-et** [comment]
Done

**Comment by wenzhixin** [comment]
It seems something error, there are 21 commits, and 7 files changed.

**Comment by bashlakov** [comment]
Maybe close this pr and I'll make a new one? Aleko-et is my colleague, we work together on same fork.

**Comment by wenzhixin** [comment]
OK, create a new one.

**Pull request closed without merging**
