### PR TITLE
Print extension

### PR DESCRIPTION
**Pull request by yaronyam**
Adds a button to the toolbar for printing the table in a predefined configurable format

### CODE REVIEW

**Comment by wenzhixin** [comment]
Can you help to provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show your extenson, thanks!

**Comment by yaronyam** [comment]
Here's a simple example: http://jsfiddle.net/yaronyam/794hsy3k/

**Comment by wenzhixin** [comment]
You can use this tool: https://rawgit.com/

**Comment by yaronyam** [comment]
I've updated the [jsfiddle ](http://jsfiddle.net/yaronyam/794hsy3k/) to use rawgit
Thanks for the tip

**Comment by wenzhixin** [comment]
Great, thanks.

**Comment by mdshaf229** [comment]
@yaronyam :  Can we have print button outside the table like this [Export button example](http://jsfiddle.net/wenyi/wc0zLpef/1/) ?

**Comment by yaronyam** [comment]
Yes @mdshaf229, if you don't mind a hackish approach - the original toolbar button can be hidden:
http://jsfiddle.net/yaronyam/794hsy3k/11/

**Comment by mdshaf229** [comment]
Yes, I don't mind this approach till we have a regular fix for this. Thanks a lot :)

**Pull request merged**
