### PR TITLE
WIP: e2e testing

### PR DESCRIPTION
**Pull request by UtechtDustin**
**Bug fix?**
no

**New Feature?**
yes

**Resolve an issue?**
no

@wenzhixin @djhvscf 
Should we add e2e tests ?

### CODE REVIEW

**Comment by djhvscf** [comment]
For sure we should add unit tests and e2e testing

**Comment by djhvscf** [comment]
@UtechtDustin at least for windows we need to add node as a prefix to this command

 "test:e2e": "_**node**_ node_modules/nightwatch/bin/nightwatch --config nightwatch.conf.js"

**Comment by UtechtDustin** [comment]
@djhvscf it should work.
The example in that PR are just a example  :-)
Should we merge this PR, so we can add e2e tests for new features and we can add the other missing tests one by one ?

**Comment by djhvscf** [comment]
> @djhvscf it should work.
> The example in that PR are just a example :-)
> Should we merge this PR, so we can add e2e tests for new features and we can add the other missing tests one by one ?

I know. But at least in windows it is a fact that we need to add node prefix to the command. This is just a FYI

**Comment by UtechtDustin** [comment]
Todo: Use the `onPostBody` ot prevent `wait` and failing tests.

**Comment by UtechtDustin** [comment]
@djhvscf Thanks for your awesome work!
I will help with that as soon i have some more time :-)

**Comment by UtechtDustin** [comment]
Lets go with #5528 and cypress.

**Pull request closed without merging**
