### PR TITLE
Moves angular integration from bootstrap-table-examples into bootstrap-table extension

### PR DESCRIPTION
**Pull request by dbkaplun**
Also adds new features, stores view information before reloading data so table doesn't thrash.

### CODE REVIEW

**Comment by djhvscf** [comment]
Great Job!

**Comment by wenzhixin** [comment]
Please update file name to bootstrap-table-angular.js

**Comment by dbkaplun** [comment]
Oops, accidentally deleted the branch. Reopened.

**Comment by wenzhixin** [comment]
Thanks!

**Pull request merged**
