### PR TITLE
Support for expand all nodes or expand just one node and added sumGroup option per column

### LINKED ISSUE #1176: pageNumber cookie issue
Hi,

Please tell me how to remove pageNumber from cookie..I dont want to store pageNumber in cookies

### PR DESCRIPTION
**Pull request by djhvscf**
Example [here](http://jsfiddle.net/e3nk137y/2441/)

Fix #1176 
Example [here](http://jsfiddle.net/081Lma9u/1/)

### CODE REVIEW

**Comment by djhvscf** [comment]
see this @andresendo

**Comment by andresendo** [comment]
after i have changed the js to your new version.. it don't load data from my json script..

**Comment by djhvscf** [comment]
@andresendo can you provide an fiddle please?

**Comment by andresendo** [comment]
Also your last server side example works with the new js not 100% clear...

http://jsfiddle.net/mfx96noa/

**Comment by andresendo** [comment]
And if the json like this:

{"total":"44","rows":
[
    {
        "id": 0,
        "name": "Item 0",
        "price": "$0"
    }
]
it don't work...

**Pull request merged**
