### PR TITLE
Use object.assign instead of extend

### PR DESCRIPTION
**Pull request by jimmywarting**
**🤔Type of Request**
- [ ] **Bug fix**
- [ ] **New feature**
- [x] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**
- part of #4796 #5526 (got to start out small)

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

**💡Example(s)?**

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by UtechtDustin** [comment]
I'm not sure if i'm a fan to use only `assign` instead of `Object.assign`.
Does this have any advantages, because it's not that readable (especially for new devs in the project).

Also i'm not sure if we should replace $.extend with `Object.assign` or if we should write our own method for that (i think we need a custom function for deep copy either way).
The `extend` function from `jquery`  is faster then `Object.assign` if [this benchmark](https://www.measurethat.net/Benchmarks/Show/3447/0/objectassign-vs-spread-vs-jqueryextend) is correct.

**Comment by jimmywarting** [comment]
Executed the test myself... it showed that spread was a clear winner and that jQuery.extend was the slowest. 
https://www.measurethat.net/Benchmarks/ShowResult/326203

using `const { assign } = Object` instead of `Object.assign` makes it a tiny bit more friendlier for the other stuff to be GC, helps with code minification and also has a faster path lookup to increase perf

anyhow this stuff didn't extend anything deeply so nothing like extend deep functionallity had to be written

**Comment by UtechtDustin** [comment]
Firefox: https://www.measurethat.net/Benchmarks/ShowResult/326214

> using const { assign } = Object instead of Object.assign makes it a tiny bit more friendlier for the other stuff to be GC, helps with code minification and also has a faster path lookup to increase perf b/c it's cached to a more closer local scope

I think our build script automatically optimize that, or not @wenzhixin  ?

**Comment by wenzhixin** [comment]
> I think our build script automatically optimize that.

Yes

**Comment by UtechtDustin** [comment]
@wenzhixin @djhvscf your opinions about this ?

**Comment by wenzhixin** [comment]
I think we can modify the code in all `src`, not just this extension.

**Comment by UtechtDustin** [comment]
@wenzhixin and what do you think about the benchmarks ?

**Comment by wenzhixin** [comment]
Updated in #6560

**Pull request closed without merging**
