### PR TITLE
Fixed getScrollPosition bug when using group by extension

### LINKED ISSUE #5197: $table.bootstrapTable('getScrollPosition'): broken when using "Group By v2 extension"
$table.bootstrapTable('getScrollPosition'): broken when using "Group By v2 extension"

https://live.bootstrap-table.com/code/Scnck/4080

error: getScrollPosition: [object Object]px

### PR DESCRIPTION
**Pull request by wenzhixin**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5197 

**Example(s)?**
Before: https://live.bootstrap-table.com/code/Scnck/4080
After: https://live.bootstrap-table.com/code/wenzhixin/4082

### CODE REVIEW

**Comment by Scnck** [comment]
Unable to verify fix you deleted solution.

**Comment by UtechtDustin** [comment]
@Scnck 
The fix is currently in our develop branch.
Example: https://live.bootstrap-table.com/code/UtechtDustin/4097

@wenzhixin 
All our example will be broken after merging and deleting the branch, we should find a way to solve that issue.
Maybe we could use a webhook after a PR is merged, then we change the selected branch in the example with the destination branch of the pullrequest.

**Comment by Scnck** [comment]
I downloaded the project referencing as such but getting "TypeError: $table.bootstrapTable is not a function" ideas to resolve
<script src="./bootstrap-table-develop/src/bootstrap-table.js"></script>

**Comment by Scnck** [comment]
when you make a change to dev can you do a quick build so that we can reference the dist files...I'm still having no luck directly referencing the src files and I try doing a build locally with no luck.

**Comment by UtechtDustin** [comment]
Do you used `type="module"` on the src file ?
Example: https://jsfiddle.net/nx0j5k8L/1/

**Comment by wenzhixin** [comment]
> Maybe we could use a webhook after a PR is merged, then we change the selected branch in the example with the destination branch of the pull request.

Added a webhook after a branch created or deleted, and check the selected branch in the example is exist, if no will auto use `develop` instead.

Now you can see that the **After** example will work well.

**Pull request merged**
