### PR TITLE
Adding third click when sorting

### LINKED ISSUE #2864: Sort reset on third click
Hello, 

I'm using bootstrap-table on my project. I expected that the third click on sorting column resets table sort.

Steps: 

- **first click:**       sort desc
- **second click:** sort asc
- **third click:**     return to default, original data

I need this behavior on my tables. 

Currently i have updated bootstrap-table.js and added some extra code to obtain the behavior.

- In BootstrapTable.prototype.DEFAULTS i add two extra properties:
```javascript
lastSortOrder : undefined,
dataUnsorted : undefined
```

- In BootstrapTable.prototype.initSort:

```javascript
var currSortOrder = this.options.sortOrder,
      lastSortOrder = this.options.lastSortOrder;

if(lastSortOrder === undefined && this.options.dataUnsorted === undefined){
  this.options.dataUnsorted = this.options.data.slice();
} else if(lastSortOrder === 'asc' && currSortOrder === 'desc'){
   this.options.sortOrder     = 'asc';
   this.options.sortName      = undefined;
   this.options.lastSortOrder = undefined;
   this.options.data          = this.options.dataUnsorted.slice();
   this.data                  = this.options.data;
   this.options.dataUnsorted  = undefined;
     return;
}

if(!(lastSortOrder === undefined && currSortOrder === 'asc'))
   this.options.lastSortOrder = currSortOrder;
```

- In BootstrapTable.prototype.onSort: 

```javascript

if (this.options.sortName === $this.data('field')) { 
   this.options.sortOrder = this.options.sortOrder === 'asc' ? 'desc' : 'asc';
} else {
   this.options.sortName = $this.data('field');

   if(this.options.lastSortOrder === undefined)
      #this.options.sortOrder = 'desc';
  else
      this.options.sortOrder = $this.data('order') === 'asc' ? 'desc' : 'asc';
}
```

### PR DESCRIPTION
**Pull request by djhvscf**
Fix #2864

Example: https://live.bootstrap-table.com/code/djhvscf/1629

### CODE REVIEW

**Comment by UtechtDustin** [comment]
Can i ask whats wrong with this PR :-) ?

**Comment by djhvscf** [comment]
Many extensions weren't working as expected

**Comment by UtechtDustin** [comment]
Oh okay

**Comment by UtechtDustin** [comment]
@djhvscf which extensions exactly had problems with that solution ?

**Comment by djhvscf** [comment]
Filter control, multisort, advanced search @UtechtDustin

**Comment by UtechtDustin** [comment]
Okay thanks, i will try that maybe next week with your code as base.
Maybe i find a fix for that :-)

**Pull request closed without merging**
