### PR TITLE
add align option for mergeCells

### PR DESCRIPTION
**Pull request by n4mlih**
no option for align so i made align option available for merging cells. When aplied to 'post-body.bs.table'. i can have mergeCells with differents align from columns header style i made..

there you can see just for last row i made align center + mergeCells it

hopefully this will usefull, thanks.

### CODE REVIEW

**Comment by martinburch** [comment]
The HTML table cell align attribute is deprecated in HTML4.01 and removed in HTML5.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#attr-align

@n4mlih n4mlih Does using bootstrap-table's existing cell style property instead, and passing a CSS property, work for you?
```
function cellStyle(value, row, index, field) {
  return {
    css: {"text-align": "center"}
  };
}
```

**Comment by n4mlih** [comment]
wow...that align already deprecated but why i can still use it??

when i do what your exactly suggest, the style attribute doesnt add to my table.. here i try to produce it in https://jsfiddle.net/9jeh3Lqk/
what i missing here??..help

thanks @martinburch

**Comment by martinburch** [comment]
@n4mlih it's just the fiddle that's messed up—something to do with how the javascript is loaded and what methods are in-scope.

Changing the "load type" of the javascript to `No wrap - in <body>` in the fiddle fixed it.
image

https://jsfiddle.net/9jeh3Lqk/3/

You can also set the cellStyle formatter in the javascript instead of reading it out of the HTML attributes. Something like this:
```
$(function () {
    $('#table').bootstrapTable({
        data: data,
        columns: [{},{},{},{cellStyle:cellStyle},{cellStyle:cellStyle},{cellStyle:cellStyle},{cellStyle:cellStyle}]
    });
});
```

**Comment by wenzhixin** [comment]
I think @martinburch is right, thanks anyway.

**Pull request closed without merging**
