### PR TITLE
Fix #6405 - Add `sortBy` method

### LINKED ISSUE #6405: Add `sortBy` method (similar as `filterBy`)
### Description

Similar as `filterBy` it would be nice to have a `sortBy` method feature.

This way a table header could look like below:

image

The "Sort by:" dropdown could call this `sortBy` method and the "Category:" dropdown would call the `filterBy` method.

### PR DESCRIPTION
**Pull request by marceloverdijk**
**🤔Type of Request**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

Fix #6405

**📝Changelog**

- [x] **Core**
- [ ] **Extensions**

**💡Example(s)?**

https://live.bootstrap-table.com/code/marceloverdijk/14888

**☑️Self Check before Merge**

⚠️ Please check all items below before reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by marceloverdijk** [comment]
@wenzhixin build fails as it cannot find the example yet.
Better the remove the example url and it later or what should I do?

**Comment by UtechtDustin** [comment]
@marceloverdijk as always create a PR for the example and the test can be started again :)

**Comment by marceloverdijk** [comment]
@UtechtDustin I've created PR https://github.com/wenzhixin/bootstrap-table-examples/pull/479 to add the example.

**Comment by wenzhixin** [comment]
@marceloverdijk Please help to update the CHANGELOG file:

```
### 1.22.0

#### Core

- **New:** Added `sortBy` method.
```

**Comment by marceloverdijk** [comment]
@wenzhixin I've added the method to the CHANGELOG.

**Review by wenzhixin — APPROVED** [review]

**Pull request merged**
