### PR TITLE
Fixed escape column option not override table option bug.

### LINKED ISSUE #6071: column.escape does not override table.escape
### Bootstraptable version(s) affected

1.19.1

### Description

Setting `escape:true` for the whole table and `escape:false` for a single column I would expect that data in all columns except this one will be escaped. But actually all data are escaped. Setting `escape` to `false` for single column does not disable escaping.

The opposite case: `escape: false` for whole table and `escape: true` for a single column works as expected.

### Example(s)

_No response_

### Possible Solutions

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by wenzhixin**
**🤔Type of Request**
- [x] **Bug fix**
- [ ] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**
Fix #6071

**📝Changelog**

- [x] **Core**
- [ ] **Extensions**

Fixed escape column option does not override table option bug.

**💡Example(s)?**
Before: https://live.bootstrap-table.com/code/wenzhixin/10759
After: https://live.bootstrap-table.com/code/wenzhixin/10760

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Review by UtechtDustin — CHANGES_REQUESTED** [review]
In the after example the column `Item Name` is not escaped, though the column don't have `data-escape="false"`.

**Review by djhvscf — APPROVED** [review]
I think it is working as expected based on the original issue

**Review by UtechtDustin — APPROVED** [review]
I guess i had again a cache issue with the editor, the after example works fine now.
@wenzhixin could you check/improve that ?

**Comment by wenzhixin** [comment]
Yes, it's a cache problem. I have updated the code, I think we can merge this PR now.

**Comment by Fanduzi** [comment]
看起来又引入了新bug. 因为当我的bootstrap-table从1.19.1升级到1.20后, 原本正常的字符乱码了. 我只设置了column escape没有设置table escape. 
不变动任何代码, 只是将bootstrap-table降级会1.19.1后, 一切又正常了
image
image

**Pull request merged**
