### PR TITLE
Introduces a new `onToggleCustomView` event

### PR DESCRIPTION
**Pull request by marceloverdijk**
**🤔Type of Request**
- [ ] **Bug fix**
- [x] **New feature**
- [x] **Improvement**
- [x] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

Introduces a new `onToggleCustomView` event to listen to this event (similar as existing `onTogglePagination` event).

**☑️Self Check before Merge**

⚠️ Please check all items below before reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by UtechtDustin** [comment]
Could you please provide two example for each event one ? :)

**Comment by marceloverdijk** [comment]
Sure, but have to that tonight after work ;-)

**Comment by marceloverdijk** [comment]
OK @UtechtDustin, I used the lunch break ;-) so here you go: https://live.bootstrap-table.com/code/marceloverdijk/13516
The examples displays a simple alert showing the current state. Works nicely.

**Review by UtechtDustin — APPROVED** [review]

**Comment by UtechtDustin** [comment]
Thank you, work fine!

**Pull request merged**
