### PR TITLE
Use options for detailView's open/close icons

### PR DESCRIPTION
**Pull request by tannermccoleman**
Puts the plus/minus icons in the that.options.icons array, and allow them to be changed using detailOpen and detailClose

### CODE REVIEW

**Comment by djhvscf** [comment]
Great! Thanks @tannermccoleman

**Comment by djhvscf** [comment]
Can you update the documentation please?

**Comment by tannermccoleman** [comment]
Sure! Just the docs for iconsPrefix or is there somewhere else they are referenced as well?

**Comment by wenzhixin** [comment]
Right, @tannermccoleman, https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/table-options.md

**Comment by tannermccoleman** [comment]
Alright, all updated! 

PS sorry for the excessive commits. I'm not good with markdown D:

**Comment by djhvscf** [comment]
Thanks

**Comment by wenzhixin** [comment]
Thanks!

**Pull request merged**
