### PR TITLE
Pagination: current page should be "active", no "disabled"

### PR DESCRIPTION
**Pull request by geeyan**
see the issue: #520

### CODE REVIEW

**Comment by geeyan** [comment]
@djhvscf  is this ok~?

**Comment by djhvscf** [comment]
Yes, It that ok! Thanks! @geeyan

**Comment by geeyan** [comment]
hah~ then I need to go to sleep..... At China, it is 03:52 now  TAT. @djhvscf

**Comment by wenzhixin** [comment]
Thanks, I will check it out soon.

**Pull request merged**
