### PR TITLE
data-formatter is not working with data-checkbox

### PR DESCRIPTION
**Pull request by jorrigala**
http://stackoverflow.com/questions/32246157/format-column-with-checkboxes-in-bootstrap-table
http://jsfiddle.net/3L7vgcx0/9/

### CODE REVIEW

**Comment by wenzhixin** [comment]
You need to update `tab` to `4 spaces`.

**Comment by jorrigala** [comment]
Added Tab to 4 spaces

**Comment by wenzhixin** [comment]
Sorry, but I think the code format is error, it seems every line is 4 spaces than the original.

**Comment by jorrigala** [comment]
Sorry for the space issues, removed extra spaces

**Comment by wenzhixin** [comment]
Sorry, need to update `src` instead of `dist` dir, I have fixed it.

**Pull request merged**
