### PR TITLE
Fix bug - 4776 - Toggle All bug when checkbox / radio column is present

### PR DESCRIPTION
**Pull request by akkivarma10**
Fixes issue #4776
Added filter for selection control columns (radio & checkbox) to fix
toggle all bug when checkbox or radio column is present.

### CODE REVIEW

**Comment by UtechtDustin** [comment]
@akkivarma10 
Thank you for the pullrequest, could you add two examples ? (before and after)

**Comment by akkivarma10** [comment]
Hi @UtechtDustin , I tried creating an example on https://live.bootstrap-table.com/, but unfortunately it isn't working. Found that it is not able to find the variables.scss file which is now renamed to _variables.scss in the new commit. Can u fix this. I will create a working example once this is done. Thanks.

**Comment by UtechtDustin** [comment]
@akkivarma10 
Good catch!
I dont have access to the editor. @wenzhixin please fix it :-)

**Comment by wenzhixin** [comment]
Fixed the online editor bug: https://live.bootstrap-table.com/code/wenzhixin/1519
Thanks for your contribution!

**Pull request merged**
