### PR TITLE
Fix #5637 one colspan in header

### LINKED ISSUE #5637: Toggle Columns in grouped headers
**Description**  
When a grouped header (aka nested) has 1 nested level (like "Price" and "Total" in the example) there is a strange behaviour: I would expect a way to hide the whole column, yet when I hide "Total", "Price" remains visible. Is there a way to hide that?
You can see it works fine in case the 2nd level header has more than 1 element: I hide `Id` and `Name` and `Key` is automatically hidden.

**Expected behaviour**  
"Price" header being hidden when I hide "Total".

**Actual behaviour**  
"Price" stays visible.

**Example**  
https://live.bootstrap-table.com/code/antonioaltamura/6940

### PR DESCRIPTION
**Pull request by ko22009**
https://live.bootstrap-table.com/code/ko22009/7031

### CODE REVIEW

**Comment by ko22009** [comment]
#5637

**Comment by ko22009** [comment]
Found problem with that template https://live.bootstrap-table.com/code/ko22009/7039

**Comment by djhvscf** [comment]
By that, you mean we can close this PR?

**Comment by ko22009** [comment]
@djhvscf, yes, I found place of mess, but I cannot create correct algorithm.

**Comment by djhvscf** [comment]
If you know where the fix could apply, let's take more time to test and then open a PR. Thanks @ko22009

**Pull request closed without merging**
