### PR TITLE
Add option for input size and icon size for filter controls

### PR DESCRIPTION
**Pull request by cyberbobjr**
This will add 2 options for choosing the size of inputs and icon of the filter-control extension :
class-size : for the class of the input
icon-size : this option exist, and it will be use by the extension for choosing the icon size of the "clear button"

### CODE REVIEW

**Comment by djhvscf** [comment]
Can you share us an example? Please

**Comment by djhvscf** [comment]
Any update here? @cyberbobjr

**Comment by cyberbobjr** [comment]
Hi,
Sorry guys, i'm very busy at this time, i'll write an example this sunday.
Bye
Regards
Cyb

Envoyé de mon iPad

**Comment by wenzhixin** [comment]
Any update?

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this PR. If you want, please create a new **PR** with this change against develop.

**Pull request closed without merging**
