### PR TITLE
WIP:Fix themes

### PR DESCRIPTION
**Pull request by dimbslmh**

### CODE REVIEW

**Comment by dimbslmh** [comment]
work in progress

**Comment by wenzhixin** [comment]
@dimbslmh Need to rebase develop branch.

**Comment by djhvscf** [comment]
Any update @dimbslmh

**Comment by djhvscf** [comment]
Hi! There is not any reply, in that case we are going to close this PR. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Comment by wenzhixin** [comment]
@dimbslmh If you are working in this please create a new PR, thanks.

**Pull request closed without merging**
