### PR TITLE
Add possibility to enable/disable which columns are gonna be used for filtering purposes 

### PR DESCRIPTION
**Pull request by mmochetti**
As the options data-searchable, data-sortable, etc are enabled in bootstrap-table, it would be great to have an option to determine which columns are possible to be filtered.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Hi @mmochetti , I am sorry it's late to handle your pull request, but I can't automatically merge this pull request now. Can you help to rebase the PR?

**Comment by mmochetti** [comment]
I did a pull / rebase on my repo and committed /pushed but didn't see you already did the merge. Can you check if everything is fine? Thanks

**Comment by djhvscf** [comment]
Can you rebase this pull request and also include an example please??

**Comment by djhvscf** [comment]
@mmochetti when you rebase this PR then reopen it or do a new PR. Thanks

**Pull request closed without merging**
