### PR TITLE
Add BS Tooltips for buttons in toolbar

### PR DESCRIPTION
**Pull request by CosmoFox**
Added  'data-bs-toggle': 'tooltip' and  'data-bs-placement': 'bottom' for buttons in toolbar (fullscreen, toggle, refresh, paginationSwitch)

**🤔Type of Request**
- [ ] **Bug fix**
- [ ] **New feature**
- [X] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

- [X] **Core**
- [ ] **Extensions**

### CODE REVIEW

**Comment by UtechtDustin** [comment]
Thank you for the PR, i have a few points:

- I guess there are more buttons as this four
- It makes sense to make the placement configurable instead of hardcoded `bottom`
- It should only be added if the used theme is a bootstrap theme
- Does all bootstrap Version have the same tooltip mechanism (data attributes) ?
- Please provide us an example using our [editor](https://live.bootstrap-table.com/).
- Please use the same syntax, `title` don't use (single) qoutes.

**Comment by CosmoFox** [comment]
> * Please use the same syntax, `title` don't use (single) qoutes.
rows with **title** are original code, i added only **,** at the end of row

For other points i need more time, cos it was fastfix for my project.

**Comment by UtechtDustin** [comment]
You're right its on the source code, but we would love if you could fix it :-)

**Comment by UtechtDustin** [comment]
Any new here @CosmoFox ?

**Comment by CosmoFox** [comment]
closing, will open new one for new version

**Pull request closed without merging**
