### PR TITLE
Multi search.

### PR DESCRIPTION
**Pull request by Nykilor**
`<table data-multi-search="SEARCH_STRING">`

Allows users to search for multiple strings for instance:
 `data-multi-search="; "`

_(sorry if I'm doing things wrong on GitHub I'm a newbie)_

Edit: the #Typo is the latest.

### CODE REVIEW

**Comment by djhvscf** [comment]
We need an example, please

**Comment by Nykilor** [comment]
Example: http://jsfiddle.net/6jp2wxpa/

**Comment by djhvscf** [comment]
Ok, I see.. But did you review this extension? https://github.com/wenzhixin/bootstrap-table/blob/develop/src/extensions/multiple-search/bootstrap-table-multiple-search.js I think it is the same, isn't it?

**Comment by Nykilor** [comment]
Yeah, looks like the same. My bad, i didn't see it in examples on site though.

**Pull request closed without merging**
