### PR TITLE
Feature/performance improve

### LINKED ISSUE #1642: initBody is evel function: extremelly slow
Hello,
I have a table with 3000 rows (it is constant number), no paging. I update that table every 2 sec with variable number of rows (1-100). I found that even update of 10 rows at once kills whole page.
The problem in 
this.initBody(true);
I am use updateRow and on each update it executes initBody. Bump.
What is could be cool, to have method updateRows and pass array of new rows there. Then use of initBody will be smaller.
In my code I just disabled initBody in updateRows and situation much better now. As I see update of data in the row cost nothing. I just introduced initBody on public level and execute it after all needed rows updated.
Having such huck makes grid useful. Only one problem, I still need to execute initBody at the end of my row update. And it is freezing page, making scrolling quite chunky. Is any optimization possible to make initBody not so heavy ? 

Thanks
Aleksey

### PR DESCRIPTION
**Pull request by wenzhixin**
Fix #1642, #3081, #3167, #4164, #4165, #4215

### CODE REVIEW

**Comment by Falseee** [comment]
After this merge i get the error `import declarations may only appear at top level of a module`
@wenzhixin

**Comment by wenzhixin** [comment]
@Falseee It's easy to use (the latest Chrome).

Build CSS:
```
yarn css:build:scss
```

Added `type="module"` to `script`:
```
<link rel="stylesheet" href="src/bootstrap-table.css">
<script src="src/bootstrap-table.js" type="module"></script>
```

BTW: updated https://github.com/wenzhixin/bootstrap-table-examples develop branch to support.

**Comment by wenzhixin** [comment]
https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7

**Comment by Falseee** [comment]
@wenzhixin 
type="module" works fine.

But if try to use the filter-control extension (with and without type="module") i get the error 
`TypeError: bootstrap is undefined (bootstrap-table-filter-control.js:580:5)`

**Comment by Falseee** [comment]
To fix that i had to change some lines..

constants/index.js added 
```
bootstrapVersion
```
to the export default object.

bootstrap-table.js added in line 2805
```
$.fn.bootstrapTable.constants = Constants
```

bootstrap-table-filter-control.js line 9
```
const Constants = $.fn.bootstrapTable.constants
```
and line 521
```
Constants.bootstrapVersion
```
instead of 
```
Utils.bootstrapVersion
```

**Comment by Falseee** [comment]
Export extension is also affect from this !

**Comment by wenzhixin** [comment]
OK, I will fix this problem.

**Comment by wenzhixin** [comment]
Added example: http://dev.bootstrap-table.com/examples/#welcomes/large-data.html

**Comment by pchaganti** [comment]
That looks pretty fast. Awesome work!

**Comment by pavanbangaloreraju** [comment]
> Added example: http://dev.bootstrap-table.com/examples/#welcomes/large-data.html

Please provide the detail of how to add in our project , as i have 100000 records and page is very slow , it takes more than 3min. please help me out

**Comment by wenzhixin** [comment]
@pavanbangaloreraju try the example: https://examples.bootstrap-table.com/#welcomes/large-data.html

**Pull request merged**
