### PR TITLE
added getVisibileColumns method for different utility.

### PR DESCRIPTION
**Pull request by enayet-repo**
There is a method for accessing hidden columns - getHiddenColumns but there is no getVisibleColumns method. 
I have searched in the library and found there is a method - getVisibleFields. But it is not accessible.
Actually adding getVisibleColumns method has more utilities especially to search on the visible columns only.
I think searching is meaning for the visible columns only, otherwise users may be confused with the searched result.

### CODE REVIEW

**Comment by djhvscf** [comment]
Fix #1941

**Comment by wenzhixin** [comment]
Sorry, this PR need to update.

**Comment by wenzhixin** [comment]
And please help to update the docs.

**Comment by enayet-repo** [comment]
Updated. Thanks

**Comment by wenzhixin** [comment]
Update docs: https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/methods.md

**Comment by enayet-repo** [comment]
Updated, thanks again.

**Comment by djhvscf** [comment]
@enayet-repo this **PR** contains a lot of commits that will break our code.. Can you create a new **PR** or revert those commits?? Please just include your new method and the documentation for that method

**Pull request closed without merging**
