### PR TITLE
Added support for X icon (IE browser)

### LINKED ISSUE #1640: Search box X icon is not working in IE browsers.
Hi,

In IE browsers bootstrap table search box will display a X icon if we enter any text. When we click on this icon it clears the text in the search box but it will not refresh the results of the table. This is happening only in IE browsers.

Is there any way to make table results to reload on click of X icon?

### PR DESCRIPTION
**Pull request by djhvscf**
Example: http://jsfiddle.net/e3nk137y/3640/

Fix #1640 

Example for alignment option (filter-control extension): http://jsfiddle.net/pbg1zesn/2/

### CODE REVIEW

**Comment by wenzhixin** [comment]
Need to rebase the code because `This branch has conflicts that must be resolved`.

**Comment by djhvscf** [comment]
Yes, I saw that.. I think we should merge the changes in the correct order.. I mean merge first the oldest pull request and so on

**Comment by wenzhixin** [comment]
Sorry, my fault.

**Comment by wenzhixin** [comment]
Please create a new PR @djhvscf, thanks!

**Pull request closed without merging**
