### PR TITLE
Fixe #1078 - the correct selectControl is updated when show/hide column

### PR DESCRIPTION
**Pull request by yenyen**

### CODE REVIEW

**Comment by wenzhixin** [comment]
The same with #1327?

**Comment by yenyen** [comment]
No it's not the same that #1327. 

This pull request resolve an issue when you hide a column then it's not the right filter-control who is updated. Please go to this jsfiddle and try to hide the name's column, you'll see that the filter-control of the item price's column is missing : http://fiddle.jshell.net/Lvo3wf2q/

This pull request fixes this problem

**Comment by wenzhixin** [comment]
20 Commits and 187 Files changed... I think do you make a mistake?

**Comment by yenyen** [comment]
Sorry, please see this pull request : #1383

**Pull request closed without merging**
