### PR TITLE
Allow HTML in "updated" column titles

### PR DESCRIPTION
**Pull request by utilmind**
eg for custom icons and tooltips over icons.

It seems wrong and illogical that column headers that normally allow HTML tags, allows only plain text upon updates.

**🤔Type of Request**
- [ ] **Bug fix**
- [ ] **New feature**
- [X ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

**📝Changelog**

- [X ] **Core**
- [ ] **Extensions**

**💡Example(s)?**

**☑️Self Check before Merge**

⚠️ Please check all items below before reviewing. ⚠️

- [ ] Doc is updated/provided or not needed
- [ ] Demo is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by wenzhixin** [comment]
**Do not edit files of `dist` directly!** Those files are automatically generated. 
You should edit the source files in [`/src/`](https://github.com/wenzhixin/bootstrap-table/tree/develop/src) instead.

**Comment by SILKCARDS** [comment]
@wenzhixin okay, updated. Now only in /src/

**Comment by utilmind** [comment]
@wenzhixin okay, updated. Now only in /src/.

**Review by wenzhixin — APPROVED** [review]

**Comment by wenzhixin** [comment]
Thanks for your contribution!

**Pull request merged**
