### PR TITLE
bug fixed: value write back

### PR DESCRIPTION
**Pull request by horkenw**
when submitted, changed value rewrite back to list

#2586

### CODE REVIEW

**Comment by wenzhixin** [comment]
When the row field is not `name` or `price`, can it work?

**Comment by horkenw** [comment]
sorry seems I make some wrong I will fixed it again.. :P I'm close this branch

**Comment by djhvscf** [comment]
I think the fields of the row can't be hard coded.. They should be dynamic

@wenzhixin @horkenw

**Comment by wenzhixin** [comment]
Yes, your are right @djhvscf

**Comment by horkenw** [comment]
Ok, I will try to do this in another way, thanks. :>  @wenzhixin @djhvscf

**Pull request closed without merging**
