### PR TITLE
Allow for multiple arguments

### PR DESCRIPTION
**Pull request by jtrumbull**
Current approach only allows for a singular argument @`_relatedTarget` passed to public
method. The new approach would allow for any amount of arguments.

__Reasoning__
I'm working on an extension and adding some additional `allowedMethods`. The methods require multiple arguments, and would ideally not have to wrap them in an object.

### CODE REVIEW

**Comment by djhvscf** [comment]
Then I think you can delete the _relatedTarget parameter

**Comment by jtrumbull** [comment]
Getting some unexpected results, will re-open when solved.

**Comment by djhvscf** [comment]
Ok.. go ahead!

**Comment by jtrumbull** [comment]
Nested function strikes again.

**Pull request merged**
