### PR TITLE
Bugfix/fix 5403

### LINKED ISSUE #5403: Incorrect row unchecked on unchecking after applying search filter.
**Bootstraptable version(s) affected**: v1.18.0

**Description**  
Steps to reproduce: 
1. Select all rows using checkbox.
2. Search for some keyword.
3. Uncheck a row from the search results.
4. Clear search box.
5. The table unchecks using index, not value. So, if first row was unchecked from search results, then first row is also unchecked from selections made in Step 1.

**Example**  
https://live.bootstrap-table.com/code/supmanyu/5191

### PR DESCRIPTION
**Pull request by djhvscf**
**Bug fix?**
Yes

**New Feature?**
No

**Resolve an issue?**
Fix #5403 

**Example(s)?**
From URL: https://live.bootstrap-table.com/code/djhvscf/5281
From Data: https://live.bootstrap-table.com/code/djhvscf/5282
From HTML: https://live.bootstrap-table.com/code/djhvscf/5283

### CODE REVIEW

**Comment by UtechtDustin** [comment]
Please resolve the CI Issues

**Comment by djhvscf** [comment]
@UtechtDustin they are related to the docs. Please review the examples repo and approve my pr :)

**Comment by djhvscf** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/pull/418

**Comment by djhvscf** [comment]
https://github.com/wenzhixin/bootstrap-table-examples/pull/418

**Comment by wenzhixin** [comment]
I don't think to add `_uid` to a row is a good idea, the bug is caused by this: https://github.com/wenzhixin/bootstrap-table/pull/5298/files. Let me have a check.

**Comment by djhvscf** [comment]
@wenzhixin why do you think that? For me is a good approach to link a `tr` to a specific object in our `data` array.

**Comment by djhvscf** [comment]
@wenzhixin any input here? I would like to discuss why _uid is not a good idea

**Comment by wenzhixin** [comment]
It will change the original data: https://live.bootstrap-table.com/code/wenzhixin/5314

**Comment by djhvscf** [comment]
Oh, yes. Actually we're iterating over both data arrays. But we'd iterate over the this.data array only and see how this behaves

**Comment by wenzhixin** [comment]
I think the key issue is the bug caused by the previous modification, which did not exist before v1.18.0: https://github.com/wenzhixin/bootstrap-table/pull/5298/files.
In addition, if there is a `_uid` field in his data, it may conflict. My suggestion is to find a better solution and re-evaluate it.

**Comment by djhvscf** [comment]
> I think the key issue is the bug caused by the previous modification, which did not exist before v1.18.0: https://github.com/wenzhixin/bootstrap-table/pull/5298/files.
> In addition, if there is a `_uid` field in his data, it may conflict. My suggestion is to find a better solution and re-evaluate it.

I got you, but I think the main problem here is that this.options.data and this.data are arrays that we use for different purposes but sometimes we use them in the wrong way.
For example, this.options.data should be immutable for me, and this.data should be the one which is filtered and etc..

What do you think @wenzhixin @UtechtDustin ?

**Comment by UtechtDustin** [comment]
I agree with @wenzhixin, i think there is a better solution for that.

**Comment by djhvscf** [comment]
Well, could you give us some ideas? I'm not sure that I'm very clear about the issue with this solution.

@wenzhixin @UtechtDustin

**Comment by wenzhixin** [comment]
I think it's a better solution for the problem: #5437

**Comment by djhvscf** [comment]
ok, close this pr @wenzhixin @UtechtDustin

**Pull request closed without merging**
