### PR TITLE
UpdateRow/updateByUniqueId extend or replace data.

### PR DESCRIPTION
**Pull request by andig89**
UpdateRow/updateByUniqueId use $.extend which only extend data (not remove attributes), so I add "replace" option.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Can you help to add documentation?

**Comment by andig89** [comment]
Hi,
yes but i don't have much time in this month, so i will try write new in next on my version. I see a lot of function to optimize/rewrite/modify so maybe i will be able to do that on writing doc 😀.

---
Regards Dariusz Gardyński

**Comment by thornomad** [comment]
Hi @wenzhixin - I can use this update as well !  I just ran into this problem myself when a value returned by the server was changed to `undefined` -- and I couldn't figure out why `updateRow` wasn't updating the row!  That's, of course, because of `$.extend()`. 

Anyhow - what do you need to be able to merge this pull request I can update the documentation.

**Comment by djhvscf** [comment]
This needs to fix the conflicts. Please open a new PR

**Pull request closed without merging**
