### PR TITLE
Fix bugs related to Filter-Control

### LINKED ISSUE #4869: Column filters not showing when using table fixed height
Hi, it seems there is a bug with the Filter Control extension when using the 'data-height' attribute on the table element. Tested on Chrome and Firefox.

You can see it in action by going on the online editor page for the Filter Control : https://live.bootstrap-table.com/example/extensions/filter-control.html and then adding a 'data-height' attribute to the table element (example: data-height="400")

It gives something like this :

image

Thanks for your help!

### LINKED ISSUE #5045: Data-filter-controls disappear on Column-switch.bs.table
"Inside the detail view, when i trigger "Get" function sub table, then perform column-switch, the data filter controls disappear."

**Step 1** when i expend the detail view, i see the "Get" button loaded. 
**Step 2** when i click the "Get" button, the Sub-table is loaded into the detail view.
**Step 3** when I try to perform Column-switch, i lose all the Data-filter controls.

 _see codepen example_:  https://codepen.io/rayzoray/pen/abvxgog

any help on how i can keep the data-filter controls would be much appreciated.

### PR DESCRIPTION
**Pull request by djhvscf**
### WORK IN PROGRESS

**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #4869
Fix #5045

**Example(s)?**
https://live.bootstrap-table.com/code/djhvscf/3819

### CODE REVIEW

**Comment by djhvscf** [comment]
image

**Comment by UtechtDustin** [comment]
@djhvscf You requested a review, but there are no examples and the titles says work in progress :D

**Comment by djhvscf** [comment]
> @djhvscf You requested a review, but there are no examples and the titles says work in progress :D

Yes sorry.. I requested that by mistake. I will let you know when this is available

**Comment by wenzhixin** [comment]
Updated the code, but I find an error: https://live.bootstrap-table.com/code/wenzhixin/3818
```js
const value = _value.trim()
```
When the _value is `0` will cause an error, please check this @djhvscf .

**Comment by djhvscf** [comment]
> Updated the code, but I find an error: https://live.bootstrap-table.com/code/wenzhixin/3818
> 
> ```js
> const value = _value.trim()
> ```
> 
> When the _value is `0` will cause an error, please check this @djhvscf .

Resolved: https://live.bootstrap-table.com/code/djhvscf/3819

**Pull request merged**
