### PR TITLE
Updated the stickyHeader offset options to number

### LINKED ISSUE #4755: sticky header offsetY not working
Hello Thanks for this project - First time using it today and its really useful! 

I have been trying the sticky Header extention and it seems to be working - Unless you try and add the stickyHeaderOffsetY 

using Local host - Uniserver - apache / php and Google chrome 

Downloaded today build to 1.15.5  

Using config   
`$table.bootstrapTable({
      stickyHeader: true,
      stickyHeaderOffsetY: 0 ,
      stickyHeaderOffsetLeft: '3em',
      stickyHeaderOffsetRight: '3em',
    });`

Outputs 
  Table looks good 
image

On scroll - Sticky seems fine .. needs offset 

image

checking on inspect : top:0px inline style
image
 

Update Config : 
`  $table.bootstrapTable({
      stickyHeader: true,
      stickyHeaderOffsetY: 60 ,
      stickyHeaderOffsetLeft: '3em',
      stickyHeaderOffsetRight: '3em',
    });`

Header is no longer Sticky : 

image

On inspect top inline style is no longer applied  

image

Unfortunately there is no on-line example at the moment, Just trying on local 

I have a quick fix by adding extra CSS
 
.sticky-header-container.fix-sticky.fixed-table-container {top: 60px;}

### LINKED ISSUE #4814: StickyHeader not working with Bootstrap container or fullscreen or offset-y
I can't get StickyHeader to work with a Bootstrap container:

1. The sticky header "jumps" out of the container, as soon as it is supposed to be at the top.
2. As well data-sticky-header-offset-y seems to have no effect: whatever value is entered, the offset is very large and always the same.
3. If fullscreen is used, the sticky header is not working at all.

Live code: [live snippet](https://live.bootstrap-table.com/code/aflogit/1612)

Replication
1. Scroll down: header "jumps" out of container
2. Change data-sticky-header-offset-y variable in HTML: no effect
3. Click on fullscreen and scroll down: header is not fixed

### PR DESCRIPTION
**Pull request by wenzhixin**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #4755
Fix #4814
#5532

**Example(s)?**
Before: https://live.bootstrap-table.com/code/dreamerworks/1701
After: https://live.bootstrap-table.com/code/wenzhixin/6645

### CODE REVIEW

**Comment by UtechtDustin** [comment]
I'm not sure if it makes sense to define px hardcoded. Maybe we should define a option for that, similar to [widthUnit](https://bootstrap-table.com/docs/api/column-options/#widthunit).

**Comment by wenzhixin** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/4755#issuecomment-666310189

> The .offset() and the .height() function returning px, so in my opinion stickyHeaderOffsetY should always be px or you have to calc how much px the % or em is you need for the const end.

I think the unit always be `px` is ok,  we can calc how much `px` the `%` or `em` something like this: https://github.com/wenzhixin/bootstrap-table-examples/pull/425

**Comment by djhvscf** [comment]
Just thinking out loud.. Could we add an option where if the `stickyHeaderOffsetLeft` is not set, then the extension assumes that it needs to calculate automagically?

**Review by djhvscf — APPROVED** [review]

**Comment by wenzhixin** [comment]
There may be different uses of cases, making it difficult to implement calculating automagically.

**Comment by djhvscf** [comment]
For me this is ok, @UtechtDustin what do you think?

**Review by UtechtDustin — APPROVED** [review]

**Comment by UtechtDustin** [comment]
It's fine for me.

**Pull request merged**
