### PR TITLE
Typo error

### PR DESCRIPTION
**Pull request by Zazou49**
**🤔Type of Request**
- [ ] **Bug fix**
- [ ] **New feature**
- [x] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

**💡Example(s)?**

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by UtechtDustin** [comment]
This is not a Typo, the slanted single qoutes are necessary to make the variable working.
You can test it with this code snippet in your browser console.
```
const test = "HELLO WORLD"
console.log('Text from variabel: ${test}')
console.log(`Text from variabel: ${test}`)
```
The result would be:
```
Text from variabel: ${test}
Text from variabel: HELLO WORLD
```

**Comment by Zazou49** [comment]
Oops, I'm sorry, thanks for the explanation ! With the commit I changed the translation of a term `Affichage` instead of `Affiche`, do I have to make a new pull request?

**Comment by UtechtDustin** [comment]
No, just revert the qoute changes, then we can merge this PR.
Sorry for my missclick (closing the PR) :D

**Review by UtechtDustin — APPROVED** [review]

**Comment by UtechtDustin** [comment]
Thank you!

**Pull request merged**
