### PR TITLE
Fix issue #4033

### PR DESCRIPTION
**Pull request by manukieli**
This path resolve the issue when you refresh browser and use Cookie + Filter Control extension and have a filter with select element.

### CODE REVIEW

**Comment by djhvscf** [comment]
Do you have an example?

**Comment by manukieli** [comment]
I've update to the version 1.14.2 and it seems now it work.

**Comment by wenzhixin** [comment]
This branch has conflicts

**Comment by manukieli** [comment]
I've create an example to Fiddle and I get another problem with the verison 1.14.2
I'm using FilterControl and Cookie.
I've set the CookieStorage like "localStorage".
When I filter the column Item Price, the filter work well.
But when I refresh the page, I get all data into table, but the filter field, appear with the last filter data before refresh and the filter is not apply.
You can see an example here: https://jsfiddle.net/pj8cktse/4/

**Comment by UtechtDustin** [comment]
Your description sounds like #2624

**Comment by djhvscf** [comment]
It is the same description @UtechtDustin

**Comment by djhvscf** [comment]
After a quick review, I'm closing this pull request since it won't solve the issue between filter control and cookie extensions.

**Comment by manukieli** [comment]
@djhvscf, can you resolve the issues???

**Pull request closed without merging**
