### PR TITLE
WIP: Fixed check/uncheck all bug when using virtualScroll option

### LINKED ISSUE #4818: selecting only 200 first rows with treegrid.js or virtualscroll enabled
https://live.bootstrap-table.com/code/yncki/1619

load 20k rows
click select all checkbox when row 0 is visible 

result:
- selected only first 200 rows 

deselect all
- scroll to rowId = 200 
- click select all checkbox 

result:
only rows 200 - 400 are selected

### PR DESCRIPTION
**Pull request by wenzhixin**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #4818 

**Example(s)?**
Before: https://live.bootstrap-table.com/code/wenzhixin/5739
After: https://live.bootstrap-table.com/code/wenzhixin/5740

Status: Work in progress

### CODE REVIEW

**Review by djhvscf — APPROVED** [review]

**Comment by UtechtDustin** [comment]
@wenzhixin you requested a review but the title still says `WIP`, what is the current status ? :-)

**Comment by wenzhixin** [comment]
After I requested a review I found a little problem that should be improved, so I update the status to WIP.

**Comment by djhvscf** [comment]
Any update @wenzhixin ?

**Comment by CheyenneRowe** [comment]
@wenzhixin  hi, i tested the examples:
Before: https://live.bootstrap-table.com/code/wenzhixin/5739
After: https://live.bootstrap-table.com/code/wenzhixin/5740

and i found a little problem:
-Step 1: Click Check all in header, then uncheck some rows.
-Step 2: Scroll the table to bottom (or any position which can trigger virtual scroll);
-Step 3: Scroll back to the position in the Step1，and the previous unchecked rows are marked as checked status.

Looking for the update~

**Comment by UtechtDustin** [comment]
I guess we can close this PR for now.
@wenzhixin will reopen it as soon there are any news.

**Pull request closed without merging**
