### PR TITLE
Fixed #1296

### LINKED ISSUE #1296: bug -- wrong row when using checkBy with filter
Hi wenzhixin,

when using checkBy with an active filter the wrong row is checked.

I've tried this with the 1.8.1 release **and** the newest commit (f65c2de217)

-- using checkBy before applying filter (**correct**)
screenshot from 2015-08-14 14 10 00

-- using checkBy after applying filter (**bug**)
screenshot from 2015-08-14 14 10 42

the first row should be checked when instead the third one is checked.

I've also tried this with other field/value pairs -- to the same effect.
(it seems the row numbers aren't updated after applying the filter).

thank you,
provivo

### PR DESCRIPTION
**Pull request by kolupaevri**
Is it a possible fixup for #1296 ?

### CODE REVIEW

**Comment by djhvscf** [comment]
Please provide a fiddle, @kolupaevri

**Comment by u01jmg3** [comment]
Should this not be in the `develop` branch?

**Comment by djhvscf** [comment]
Any update here?? @kolupaevri and also remember that you have to do the Pull Request against develop branch

**Comment by dabros** [comment]
@kolupaevri - please provide fiddle to prove changes, then make PR for develop branch

https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md

thanks

**Comment by wenzhixin** [comment]
close this issue because there is no response long time.

**Pull request closed without merging**
