### PR TITLE
Fix bug - No data in cell, if data-field are not in the last line of the header

### PR DESCRIPTION
**Pull request by akkivarma10**
In case of multiple header rows, the row with data-field was not being considered
unless it was the last row.

### CODE REVIEW

**Comment by akkivarma10** [comment]
Fixes the issue #4683

**Comment by wenzhixin** [comment]
There are still bugs when you switch fields.

image

https://live.bootstrap-table.com/code/wenzhixin/1368

**Comment by akkivarma10** [comment]
Ohh, I see. I also checked the example from the issue link & found that this issue is there also. Will look into it.

**Comment by wenzhixin** [comment]
ref #3213, but I think it's hard to implement.

**Comment by djhvscf** [comment]
Any update here?

**Comment by djhvscf** [comment]
Close this PR because there is no any response in 7 days, if the problem exists reopen it, thanks!

**Pull request closed without merging**
