### PR TITLE
Add select2 filter & i18n enhance extensions

### PR DESCRIPTION
**Pull request by jewway**
1. select2 filter extension. (dependency select2 v4.0.2)
2. i18n enhance extension  API support to change table title by locale. (update DOM  immediately.)

### CODE REVIEW

**Comment by djhvscf** [comment]
Please add the Read.ME and extension.json files

**Comment by djhvscf** [comment]
And algo add examples of this extensions

**Comment by jewway** [comment]
Done, wait for you review. 
Thanks.

**Comment by wenzhixin** [comment]
Thanks!

**Pull request merged**
