### PR TITLE
add data-data-field option for compability with different REST backends

### PR DESCRIPTION
**Pull request by bashlakov**
Ability to customize this option will let more simply integration with backend. Default value is backward-compatibility with current realization.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Can you help to update the docs

**Comment by bashlakov** [comment]
Yes, but I can't understand, which files I need to edit. Could you point me?
Also my English is very poor, and don't know Chinese and Spanish :(

**Comment by djhvscf** [comment]
This is the document that you have to update https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/table-options.md

**Comment by bashlakov** [comment]
Ready. How I can locally see docs in browser?

**Comment by wenzhixin** [comment]
Thanks!

**Pull request merged**
