### PR TITLE
 bootstrap-table-group-by-v2 collapse/expand 

### LINKED ISSUE #5007: bootstrap-table-group-by-v2 collapse/expand
Can you please include a feature that the bootstrap-table-group-by-v2 plugin can collapse/expand ?

https://examples.bootstrap-table.com/#extensions/group-by-v2.html

thank you!

### PR DESCRIPTION
**Pull request by UtechtDustin**
**Bug fix?**
no

**New Feature?**
yes

**Resolve an issue?**
Fix #5007

**Example(s)?**
Cant provide Examples because the are dont compiled, so the examples in the editor cant work.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Can add an example like this: https://live.bootstrap-table.com/code/wenzhixin/3978

**Comment by timoline** [comment]
great!!! thx

is it default collapsed or expanded?
maybe add a setting for this?

**Comment by UtechtDustin** [comment]
@timoline 
As default the groups are expanded.
Could you open a issue to for that setting ?

**Comment by timoline** [comment]
ok done
#5181

**Pull request merged**
