### PR TITLE
Reworded 'Reporting Issues' and added link

### PR DESCRIPTION
**Pull request by dabros**
CONTRIBUTING.md seems ignored by many users, especially as it relates to Reporting Issues as well as code contributions, and has some great content to help with that process. So highlighted this and linked to it from README.md

### CODE REVIEW

**Comment by wenzhixin** [comment]
Submit to develop branch?

**Comment by dabros** [comment]
@wenzhixin - sorry bout that, dont have an environment atm so just using online interface. Can you move it there or do i have to remake the changes? (bit rusty with git itself)

**Comment by wenzhixin** [comment]
Merged #1669

**Comment by dabros** [comment]
@wenzhixin - thanks, ill keep that in mind :)

**Pull request closed without merging**
