### PR TITLE
 UniqueId can also be stored in a row's data property

### PR DESCRIPTION
**Pull request by tmazur**
eg. `<tr data-unique-id="id1"> `...

### CODE REVIEW

**Comment by djhvscf** [comment]
:+1:

**Comment by djhvscf** [comment]
This PR must be against to develop branch @tmazur

**Comment by tmazur** [comment]
Should I close this PR and create a new one? The CONTRIBUTING.md doc on master branch says to create a PR based on develop branch, however the same document on develop branch, says to do this on the master branch.

**Comment by wenzhixin** [comment]
please close this and create a new PR, thanks.

**Pull request closed without merging**
