### PR TITLE
Add a toggle pagination toolbar button

### PR DESCRIPTION
**Pull request by Timmy72**
To allow user to set options.pagination to true/false.
Useful to display all table row, and then export them for example.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Hi, can you help add an example here: https://github.com/wenzhixin/bootstrap-table-examples, use the template: https://github.com/wenzhixin/bootstrap-table-examples/blob/master/template.html.
And modify:
```
<script src="bootstrap-table/bootstrap-table.js"></script>
```
to:
```js
<script src="https://rawgit.com/Timmy72/bootstrap-table/master/src/bootstrap-table.js"></script>
```

Thanks for your Pull Request.

**Comment by Timmy72** [comment]
You just have to add 

    data-show-pagination-switch="true"

in the table attributes. That's all.
A button appear in toolbar to allow you to set pagination to true/false.

Example 424 is pushed.

**Comment by wenzhixin** [comment]
Thanks, I will check it out as soon as possible.

**Comment by Timmy72** [comment]
You're welcome, very nice work on your part.

Le Tue Jan 13 2015 at 10:40:50, 文翼 <notifications@github.com> a écrit :

Thanks, I will check it out as soon as possible.

**Comment by djhvscf** [comment]
:+1:

**Comment by wenzhixin** [comment]
Merged. Need to update locales and documentation, can you help to update the documentation?

**Comment by Timmy72** [comment]
Of course. What do you need more precisely ?
+ I'm french, so if there are french translations to do, ask me.

Le Wed Jan 14 2015 at 10:30:16, 文翼 <notifications@github.com> a écrit :

Merged. Need to update locales and documentation, can you help to update

**Comment by wenzhixin** [comment]
`showPaginationSwitch` option and `togglePagination` method:
https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/table-options.md
https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/methods.md

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/424.html

**Comment by scred3** [comment]
Hi,

http://issues.wenzhixin.net.cn/bootstrap-table/#424.html -> 404 Not Found

**Comment by wenzhixin** [comment]
http://issues.wenzhixin.net.cn/bootstrap-table/#issues/424.html

**Pull request merged**
