### PR TITLE
Add data-card-visible column option

### PR DESCRIPTION
**Pull request by djhvscf**
Ref to: https://github.com/wenzhixin/bootstrap-table/issues/192 for data-card-visible option
Ref to: https://github.com/wenzhixin/bootstrap-table/issues/209 for data-key-events option
Ref to: https://github.com/wenzhixin/bootstrap-table/issues/442 for data-search-text option
Ref to: https://github.com/wenzhixin/bootstrap-table/issues/435 for 'All' options in page size list
Ref to: https://github.com/wenzhixin/bootstrap-table/issues/590 for pagination options

### CODE REVIEW

**Comment by wenzhixin** [comment]
:+1: Cool, I would check it out as soon as possible.

**Comment by djhvscf** [comment]
Hehe... It was a lot of work... But I enjoyed it

**Comment by wenzhixin** [comment]
I am a little busy these days, thank you for the maintenance of this project.

**Comment by djhvscf** [comment]
Yes, No problem. I tried to help you :)

**Comment by wenzhixin** [comment]
The most important thing is that we can help others :)

**Comment by djhvscf** [comment]
Exactly! You're right! :+1:

**Comment by wenzhixin** [comment]
A question, what chat tools do you use usually? I am using [hangouts](https://chrome.google.com/webstore/detail/hangouts/knipolnnllmklapflnccelgolnpehhpl).

**Comment by djhvscf** [comment]
Hangouts. :) @wenzhixin

**Pull request merged**
