### PR TITLE
Updated Documentation

### LINKED ISSUE #4846: Cell input/Pipeline extension missing documentation
The cell input extension is not documented (didnt knew that extension exists until now).
@wenzhixin The extension is also not selectable on the online editor.

### PR DESCRIPTION
**Pull request by UtechtDustin**
Fix #4846

### CODE REVIEW

**Comment by wenzhixin** [comment]
I need to check the example of extension is working well.

**Comment by UtechtDustin** [comment]
@wenzhixin any news here ?

**Comment by wenzhixin** [comment]
I will check this asap.

**Comment by wenzhixin** [comment]
Fixed in #4957

**Pull request closed without merging**
