### PR TITLE
Update bootstrap-table-sk-SK.js

### PR DESCRIPTION
**Pull request by neisor**
Updated and added sk-SK (Slovak) translations for bootstrap table.

**Bug fix?**
no

**New Feature?**
yes - added translations

### CODE REVIEW

**Review by UtechtDustin — APPROVED** [review]

**Comment by UtechtDustin** [comment]
Thank you for your contribution :-)

**Comment by djhvscf** [comment]
@UtechtDustin this was directly to master

@wenzhixin FYI

**Comment by UtechtDustin** [comment]
Oh your right, should we revert it or should we let it as it is ?
It should not matter, i guess.

**Comment by djhvscf** [comment]
I think we should merge master into develop then

**Comment by wenzhixin** [comment]
I have merged into `develop` and revert from `master` branch.

**Pull request merged**
