### PR TITLE
theme support

### LINKED ISSUE #4258: Bootstrap 4 Multi Sort Support
The ["Multiple Sort"](https://examples.bootstrap-table.com/index.html#extensions/multiple-sort.html) plugin (`showMultiSort`) for Bootstrap Tables is broken for Boostrap 4. The demo on the linked page is visibly broken. The button is visible in the DOM, but it appears "hidden" to the user.

## Workaround

I posted a self-answered question on Stackoverflow that provides a possible workaround.

>https://stackoverflow.com/questions/55401039/bootstrap-tables-multiple-sort-broken-for-bootstrap-4

```js
(function($) {
  $.fixBootstrapMultisort = function() {
    let $button = $('.multi-sort'),
      $modal = $('div[id^="sortModal_"].modal'),
      $toolbar = $modal.find('.modal-dialog #toolbar');
    // Wrap the button in a button group element.
    $button.addClass('btn-secondary').wrap($('<div>').addClass('btn-group'));
    // Fix modal title alignment.
    $modal.find('.modal-dialog .modal-content .modal-header .modal-title').css({ position: 'absolute', lineHeight: 1 });
    // Fix the icons.
    $button.find('.fa.glyphicon-sort').removeClass('glyphicon-sort').addClass('fa-sort').css('width', '1em');
    $toolbar.find('i.glyphicon-plus').removeClass('glyphicon-plus').addClass('fa-plus');
    $toolbar.find('i.glyphicon-minus').removeClass('glyphicon-minus').addClass('fa-minus');
  };
})(jQuery);
```

There were a few things I had to fix.

- The `.multi-sort` button was not wrapped in a `div.btn-group` element.
- The icon was a `.glyphicon-sort` rather than `.fa-sort`.
- I set the width of the button to `1em`, because it was defaulting to the width of the icon.
- The modal window title was not on the left.

Call it after your table creation.

```js
$('#table').bootstrapTable({
  showMultiSort: true
});
$.fixBootstrapMultisort();
```

### PR DESCRIPTION
**Pull request by UtechtDustin**
fix #4258 

This fix is for a temporary support of themes until @dimbslmh has rewritten the extension.

Demo: http://jsfiddle.net/r17pwmse/1/

### CODE REVIEW

**Comment by djhvscf** [comment]
Need an example, please

**Comment by UtechtDustin** [comment]
example of one theme or of all themes ?

**Comment by djhvscf** [comment]
A bootstrap theme at least! :)

**Comment by UtechtDustin** [comment]
Added an bootstrap example.

**Comment by djhvscf** [comment]
Should the select control has the form-control class?

**Comment by UtechtDustin** [comment]
Yes i agree, added the form-control class (for bootstrap).

**Comment by djhvscf** [comment]
The sort button is not working. Can you check? It looks like it is not finding this element 

` let $alert = that.$sortModal.find('div.alert')`

On this function:

`that.$sortModal.off('click', '.multi-sort-order-button').on('click', '.multi-sort-order-button', () => {...`

**Comment by UtechtDustin** [comment]
The sort button works fine for me ;o

**Comment by UtechtDustin** [comment]
Updated, the bootstrap theme has now the `from-control` and also will close the modal while sorting.
I also tested all themes for the same behavior.

**Pull request merged**
