### PR TITLE
Fix for: Multiple-sort with multiple tables is not working #959

### PR DESCRIPTION
**Pull request by dimbslmh**
Fix for: Multiple-sort with multiple tables is not working #959

Adding multiple tables support

### CODE REVIEW

**Comment by djhvscf** [comment]
@wenzhixin I already tested this PR, it is working

**Comment by wenzhixin** [comment]
I think there is something wrong with the commits, are you using to the following process: https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests

**Comment by dimbslmh** [comment]
For this PR yes. I missed this process for my previous PR.

**Comment by djhvscf** [comment]
I can close this PR a do a new one with the changes that you made.. what do you think @dimbslmh ?

**Comment by dimbslmh** [comment]
No problem. I'll delete and fork a new master afterwards.

**Comment by djhvscf** [comment]
Close this PR.

See this one: https://github.com/wenzhixin/bootstrap-table/pull/993

**Pull request closed without merging**
