### PR TITLE
Increment totalRows and pageSize on row insertion in server mode

### PR DESCRIPTION
**Pull request by OnlyPassionCode**
**🤔Type of Request**
- [x] **Bug**

- [x] **Core**

**☑️Self Check before Merge**

⚠️ Please check all items below before reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by wenzhixin** [comment]
Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

**Comment by OnlyPassionCode** [comment]
> Please provide an [Online Example](https://live.bootstrap-table.com) to show your problem. Thanks!

Here is a example : https://live.bootstrap-table.com/code/OnlyPassionCode/17570

**Comment by wenzhixin** [comment]
After Example: https://live.bootstrap-table.com/code/wenzhixin/17572 with your branch.

**Comment by OnlyPassionCode** [comment]
> After Example: https://live.bootstrap-table.com/code/wenzhixin/17572 with your branch.

I just made a correction.

In fact when inserting data, I increased the pageSize variable by 1 but the problem is that this variable is not reset during the next initServer.
So I created a backUp system in order to reset this pageSize variable.
Additionally, now in the insertRow the this.data variable contains the options data, why is this important? This is due to another bug which consists of when we add a row at index 0 and we want to modify the row at index 1 by clicking on it for example and the event gives us the 'index 1 but actually gives us the row with index 2 because he did not put our new row in this.data because we are in server mode.

**Comment by OnlyPassionCode** [comment]
Here is an example of a use case where we would like to retrieve the row clicked following the insertion of a row : 
https://live.bootstrap-table.com/code/OnlyPassionCode/17573

**Comment by OnlyPassionCode** [comment]
Here is an example of the final usage, but I don't understand.
The libraries section does not take my latest commits and therefore it does not work.

https://live.bootstrap-table.com/code/OnlyPassionCode/17574

**Comment by OnlyPassionCode** [comment]
I'm going to work on a cleaner system closer to that of client mode. And of course the debugs of the bugs that I cited too

**Pull request closed without merging**
