### PR TITLE
Extension Multiple Sort Support Server Pagination

### PR DESCRIPTION
**Pull request by bleeloe**
Multisort extenson now support pagination server mode. added url array param 
`&multiSort[0][sortName]=field_one&multiSort[0][sortOrder]=asc&multiSort[1][sortName]=field_two&multiSort[1][sortOrder]=asc`

### CODE REVIEW

**Comment by djhvscf** [comment]
You don't have to modify the dist/ files

**Comment by bleeloe** [comment]
sorry new guys here...

i have made change in src

**Comment by AndrejGajdos** [comment]
@bleeloe I think you should add condition `&& that.options.sidePagination !== 'server'`

```
this.$el.on('load-success.bs.table', function() {
                if (!isSingleSort && that.options.sortPriority !== null && typeof that.options.sortPriority === 'object' && that.options.sidePagination !== 'server') {
                    that.onMultipleSort();
                }
            });
```

You don't want to use multiSort function after table loading, if you use server side paging.

**Comment by wenzhixin** [comment]
Thanks! Merged in
https://github.com/wenzhixin/bootstrap-table/commit/1d19c0ddf76fab0635d33f8980007dade9af64a2

**Pull request closed without merging**
