### PR TITLE
Bootstrap Table Multiple Sort extension

### PR DESCRIPTION
**Pull request by dimbslmh**
Hi @wenzhixin ,

I made this extension for sorting by multiple columns https://github.com/wenzhixin/bootstrap-table/issues/70:

http://jsfiddle.net/dimbslmh/s2h1gzj9/

### CODE REVIEW

**Comment by wenzhixin** [comment]
Great!!! Thanks @dimbslmh

**Comment by jtrumbull** [comment]
@dimbslmh: Great extension! Excited to start playing around with this.

Do you guys think it would be appropriate to come up with a procedure for creating an extension, and adding it to the CONTRIBUTING.md?

One suggestion you may consider is having a separate repository for each extension. This would allow for the extension developer to manage pull requests on their project, then the core developer to manage pull requests of the extension into the root library.

I.e.
### Creating an extension
1) Create a separate repository for your extension `[username]/bootstrap-table-your-extension`
2) Fork the `bootstrap-table` project (See steps 1-3 in [Pull requests](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests))
3) Add/Modify `your-extension` at `src/extensions/your-extension`
4) Continue through steps 4-6 in [Pull requests](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests).
5) Create a pull request for your extension (Step 7 in [Pull requests](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#pull-requests)).
 
Just a thought, wasn't sure where else to post general discussion.

**Comment by dimbslmh** [comment]
@wenzhixin @jtrumbul Thank you.

@jtrumbul Yeah, is see what you mean. I forgot to create my own separate repository of the extension (separated from the main bootstrap-table repository).

**Comment by djhvscf** [comment]
@janborup I agree with that.. good idea.. what do you think @wenzhixin ?

**Comment by djhvscf** [comment]
No problem @dimbslmh  we are trying to define the process! ;)

**Comment by wenzhixin** [comment]
Thanks for your advice @jtrumbull, that sounds great! Just what I said in [Using the issue tracker](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md#using-the-issue-tracker), it is better for the extension developer to manage their project.

**Comment by wenzhixin** [comment]
Can you help to add the process to [CONTRIBUTING.md](https://github.com/wenzhixin/bootstrap-table/blob/master/CONTRIBUTING.md) @jtrumbull ?

**Comment by wenzhixin** [comment]
@dimbslmh if you have time it is great to add an example to [bootstrap-table-examples](https://github.com/wenzhixin/bootstrap-table-examples/tree/master/extensions) repo :), pull request is welcome.

**Comment by jtrumbull** [comment]
@wenzhixin: Sure thing, i'll write something up.

**Comment by dimbslmh** [comment]
@wenzhixin Yes, I'll try to make one now.

**Comment by dimbslmh** [comment]
@wenzhixin See [multiple-sort.html](https://github.com/wenzhixin/bootstrap-table-examples/pull/32/files)

**Comment by wenzhixin** [comment]
Added docs: http://bootstrap-table.wenzhixin.net.cn/extensions/#table-multiple-sort

**Comment by dimbslmh** [comment]
Please let me know if you find any bugs. Thank you.

**Comment by djhvscf** [comment]
Ok, Thanks

**Pull request merged**
