### PR TITLE
Added titles to the export and filter-control buttons

### PR DESCRIPTION
**Pull request by jermeyjungbeker**
Added titles to the export and filter-control buttons that are displayed on the top of a table.

### CODE REVIEW

**Comment by wenzhixin** [comment]
can you use http://bootstrap-table.wenzhixin.net.cn/documentation/#localizations to define to locales?

**Comment by jermeyjungbeker** [comment]
Was really busy the last couple of days i will see what i can do.

**Comment by wenzhixin** [comment]
For example like: `formatExport`, `formatClearFilters`.

**Comment by jermeyjungbeker** [comment]
Just wondering how do i get the current localization that is set in bootstrap table? Currently i have it as BootstrapTable.LOCALES['en-US'].formatExport().

**Comment by djhvscf** [comment]
@jermeyjungbeker you must use the locales like this one: https://github.com/wenzhixin/bootstrap-table/blob/develop/src/bootstrap-table.js#L1017, for example: `this.options.formatExport();`

**Comment by wenzhixin** [comment]
Merged in #2279

**Pull request closed without merging**
