### PR TITLE
Fixing the issues of flatJSON

### PR DESCRIPTION
**Pull request by djhvscf**

### CODE REVIEW

**Comment by wenzhixin** [comment]
Which issues?

**Comment by dimbslmh** [comment]
https://github.com/wenzhixin/bootstrap-table/issues/686
https://github.com/wenzhixin/bootstrap-table/issues/688

**Comment by wenzhixin** [comment]
OK!

**Comment by dimbslmh** [comment]
Sorry @wenzhixin, those issues were not fixed yet with this commit.

**Comment by wenzhixin** [comment]
Oh..

**Pull request merged**
