### PR TITLE
Support editable obj.field1.field2

### PR DESCRIPTION
**Pull request by chenchuxin**
```
obj = { field1: { field2: 2 } };
```
When I use editable to edit field2, `obj` will and a field" `field1.field2: 2`".
This pull request fixed it.

### CODE REVIEW

**Comment by chenchuxin** [comment]
Sorry，my first commit has bug。。。

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show this PR working, thanks!

**Comment by djhvscf** [comment]
Please provide a [jsFiddle](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports) to show this PR working, thanks!

**Comment by djhvscf** [comment]
Hi! There is not any reply, in that case we are going to close this PR. Remember to add an [example](https://github.com/wenzhixin/bootstrap-table/blob/develop/CONTRIBUTING.md#bug-reports). Thanks!

**Pull request closed without merging**
