### PR TITLE
fix/4851

### LINKED ISSUE #4851: Toolbar extension only works for bootstrap themes
The toolbar extension only works for the bootstrap themes.

Example (in that case for bulma): https://live.bootstrap-table.com/code/UtechtDustin/1709

### PR DESCRIPTION
**Pull request by UtechtDustin**
fix #4851 

Bootstrap 4: https://live.bootstrap-table.com/code/UtechtDustin/1729
Bootstrap 3: https://live.bootstrap-table.com/code/UtechtDustin/1728
Materialize: https://live.bootstrap-table.com/code/UtechtDustin/1726
Semantic: https://live.bootstrap-table.com/code/UtechtDustin/1725
Foundation: https://live.bootstrap-table.com/code/UtechtDustin/1727
Bulma: https://live.bootstrap-table.com/code/UtechtDustin/1724

### CODE REVIEW

**Comment by UtechtDustin** [comment]
I will fix the X for the modal, but on semantic its working normal for me.
Which browser do you use ?
Bildschirmfoto von 2020-02-09 11-24-59

**Comment by wenzhixin** [comment]
Updated this branch, need to `git pull --rebase`

**Comment by wenzhixin** [comment]
image

Can we improve the input style of Bulma?

**Comment by UtechtDustin** [comment]
@wenzhixin 
What do you exactly mean ?
Do you mean the blank space on the right ?

**Comment by wenzhixin** [comment]
> in the semantic example is rendering the table as a card view

Fixed in #4857

@UtechtDustin 

Added the `input` class to the input element:

image

**Comment by UtechtDustin** [comment]
Done, can be reviewed.

**Comment by UtechtDustin** [comment]
> The x on the bulma example is not working

Forgott that point, sorry.
Its fixed now :-)

**Pull request merged**
