### PR TITLE
Fix #4578

### LINKED ISSUE #4578: Default search and filterControl search bug
Hello

FilterControl (filterControl: true) works correctly without default search (search: false)

FilterControl (filterControl: true) works incorrectly with default search (search: true) : 

**When I remove search text / selected values from filtercontrol inputs (empty all), then data is not changed back, but still filtered by prev search text from filtercontrol (bug only with search: true, else it changes data back on empty inputs correctly)**, also problem with cursor changing automatically position from default search to filtercontrol inputs (if you search first by filter inputs and then go to default search it will change cursor back to filter input)...

Tested on latest Chrome.

### PR DESCRIPTION
**Pull request by djhvscf**
Fix #4578

### CODE REVIEW

**Comment by djhvscf** [comment]
@wenzhixin @DustinUtecht The PR is complete now. Please review it again

**Comment by djhvscf** [comment]
@wenzhixin @UtechtDustin

**Comment by UtechtDustin** [comment]
Im currently busy, i will checked as soon i have time.

**Comment by wenzhixin** [comment]
Working example: https://live.bootstrap-table.com/code/wenzhixin/1630

**Pull request merged**
