### PR TITLE
Added an option to set the default value

### LINKED ISSUE #2487: Looking to apply default filter with the 'filter-control' extention
I am using 'filter-control' and I would like to find some method to apply a default column filters as the table is created.

Would be nice if I could put something on the column definition to set the default filter
`<th data-field="scope" data-filter-control="select" data-filter-control-default="live" >Scope</th>`

### PR DESCRIPTION
**Pull request by UtechtDustin**
Added an option to set a default filter for for the filter-control extension, based on the PR https://github.com/wenzhixin/bootstrap-table/pull/3468.

Would fix #2487.

### CODE REVIEW

**Comment by UtechtDustin** [comment]
@djhvscf You closed the PR #3468 because the src was not updated, was that just a conflict with a new version or was there a bug ?

**Comment by UtechtDustin** [comment]
force pushed same commit for trigger the ci

**Comment by djhvscf** [comment]
@UtechtDustin please update the docs

**Comment by djhvscf** [comment]
> @djhvscf You closed the PR #3468 because the src was not updated, was that just a conflict with a new version or was there a bug ?
> 
> Could you also tell me for what [this line](https://github.com/wenzhixin/bootstrap-table/pull/4389/files#diff-772b629b8b2aff7199f0c8b1ae47624eL289) is, i think its obsolete (is it?) ?

Yes, that line is obsolete. You could remove it

**Comment by UtechtDustin** [comment]
Added documentation.

Demo: http://jsfiddle.net/fqompckr/2/

**Comment by lastik228** [comment]
prompt and how to connect filter default to select?               so, unfortunately, not connected <th data-field="active" data-filter-control="select" data-sortable="true" data-filter-default="Yes">work</th>

**Comment by lastik228** [comment]
<th data-field="active" data-filter-control="select" data-sortable="true" data-filter-default="Yes">work</th>

**Comment by lastik228** [comment]
prompt and how to connect filter default to select?               so, unfortunately, not connected "<th data-field="active" data-filter-control="select" data-sortable="true" data-filter-default="Yes">work</th>"

**Comment by lastik228** [comment]
prompt and how to connect filter default to select?               so, unfortunately, not connected ' th data-field="active" data-filter-control="select" data-sortable="true" data-filter-default="Yes" 'work'/th'

**Comment by dpandey-covalience** [comment]
hey i am getting issues while implementing defaultFilter. can anyone help me.

**Comment by davinderpandey** [comment]
I am getting issue while implementing filterDefault. can anyone help me.
i am using jquery.
below are the options which i am using
  filterControl: 'select',
  ilterData:detailDataTO,
 filterDefault:"17842",

**Pull request merged**
