### PR TITLE
Added example to docs for rowStyle and cellStyle

### PR DESCRIPTION
**Pull request by thornomad**
It wasn't immediately clear what should be returned by the rowStyle and cellStyle functions; this example should help clarify.

### CODE REVIEW

**Comment by dabros** [comment]
@thornomad - thanks for that

Though btw, maybe another quick commit to add code block / pre / whatever to html in `sortName`, to be consistent with above inline html, as well as character "e" outsite table (click 'view whole file')

Just pass-by-observations ;)

**Comment by thornomad** [comment]
@dabros - I can add another commit for `sortName` ... sure.

As for the "e" ... I haven't a clue where that is coming from and think it may be generated from Markdown by some strange twist of fate.  It was there before I got to it.  Tell me how to remove it and I will.

http://bootstrap-table.wenzhixin.net.cn/documentation/#column-options

D

**Comment by wenzhixin** [comment]
Thanks!

**Comment by wenzhixin** [comment]
"e" problem: https://github.com/wenzhixin/bootstrap-table/commit/48c188d0ad2fb28509f0ede1e44113cb8340ee69

**Pull request merged**
