### PR TITLE
Code consistency

### PR DESCRIPTION
**Pull request by djhvscf**
Fixed some inconsistencies with if statement and some "returns "

### CODE REVIEW

**Comment by wenzhixin** [comment]
One question, in our source we use 4 spaces intead of tab.

**Comment by djhvscf** [comment]
Yes you're right, I didn't see how source was uploaded!!  Sorry for that.. It was my mistake.. You can close this pull request and no merge it, if your want.

**Comment by wenzhixin** [comment]
Merged, I mean here is not aligned:

**Comment by wenzhixin** [comment]
Thanks:)

**Pull request merged**
