### PR TITLE
Added custom functions

### LINKED ISSUE #1956: Custom search function
Hi, great library...question: is there a way to explicit a custom function to do the search? I'm trying to implement a search like:

"<10" and filter all elements that are less than 10

I can't find any method/event related to this.

### PR DESCRIPTION
**Pull request by djhvscf**
Fix #1956 
Example: http://jsfiddle.net/djhvscf/e3nk137y/4594/
___________________________

### CODE REVIEW

**Comment by wenzhixin** [comment]
Thanks @djhvscf , can you help to add `showAllColumns` and `hideAllColumns` to documentation?

**Comment by djhvscf** [comment]
Sure

**Comment by djhvscf** [comment]
@wenzhixin Documentation added in #2027

**Comment by Leprosy** [comment]
Are there any customSearch documentation? Is there a way to set this using html data attributes?

**Comment by Leprosy** [comment]
Is this in the last version of the library? Is there any documentation?

**Comment by djhvscf** [comment]
No, this feature is not released yet. There is documentation but it is in the develop branch @Leprosy

**Comment by Leprosy** [comment]
Awesome, thanks!!

**Pull request merged**
