### PR TITLE
add alternative group-by extension

### PR DESCRIPTION
**Pull request by Knoxvillekm**
http://jsfiddle.net/Knoxvillekm/byv2pk24/

### CODE REVIEW

**Comment by djhvscf** [comment]
:+1:

**Comment by wenzhixin** [comment]
Please add an `extension.json` file, for example: https://github.com/wenzhixin/bootstrap-table/issues/1606

**Comment by Knoxvillekm** [comment]
@wenzhixin, added

**Comment by wenzhixin** [comment]
Thanks!

**Pull request merged**
