### PR TITLE
Hide stateField before export and show after

### PR DESCRIPTION
**Pull request by Flounn**

### CODE REVIEW

**Comment by djhvscf** [comment]
Please provide an example

**Comment by Flounn** [comment]
I have a t

**Comment by djhvscf** [comment]
Got it! @Flounn

**Comment by djhvscf** [comment]
@wenzhixin canyou take a look here?

**Comment by Flounn** [comment]
A merge?

**Comment by Flounn** [comment]
@wenzhixin Updated

**Comment by wenzhixin** [comment]
Thanks for your contribution!

**Pull request merged**
