### PR TITLE
fix/5427

### LINKED ISSUE #5427: Filter control with sortable
**Bootstraptable version(s) affected**:
1.18

**Description**  
I have data-search, data-sortable, data-filter-control option. In data-search, I have used search on enter key. so when I try to search on a column-based there I need to hit enter to search, but when I hit the enter key the column gets searched with text and the same column which is getting sorted. The sort should not happen.

**Example**  
https://live.bootstrap-table.com/code/rahulpattanshetty/5375

data-search-on-enter-key="true" should not be applied to data-filter-control input box

### PR DESCRIPTION
**Pull request by UtechtDustin**
Maybe i miss something, but i dont know why we should need that code.
We only have inputs in the header which can be selected with the keyboard (shift).

**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5427

**Example(s)?**
Before: https://live.bootstrap-table.com/code/rahulpattanshetty/5375
After: https://live.bootstrap-table.com/code/UtechtDustin/5401

### CODE REVIEW

**Comment by djhvscf** [comment]
This is to support tab and space behavior over the headers. I think we shouldn't remove this

**Comment by wenzhixin** [comment]
Agree with @djhvscf

**Comment by UtechtDustin** [comment]
Could you please explain that ?
Im not able (or don't know how) to sort with tab/space.

**Comment by djhvscf** [comment]
Well... after a review looks like that functionality was removed. We usually add tabindex to the th elements in order to support tab+enter = sort

**Comment by UtechtDustin** [comment]
So the question is, can we merge this PR ?
This code will cause the bug of #5427, the sort via space+tab is currently not possible and i don't think that a lot of ppl will sort via tab+space.

**Review by djhvscf — APPROVED** [review]

**Comment by djhvscf** [comment]
For my perspective it is ok. @wenzhixin what do you think?

**Comment by UtechtDustin** [comment]
@wenzhixin  What do you think ?

**Comment by UtechtDustin** [comment]
@wenzhixin Still waiting :-)

**Comment by wenzhixin** [comment]
The related issue and commit: #1393  https://github.com/wenzhixin/bootstrap-table/commit/7e489d06cd0b87c4736010dd2e62735abc3805f6

**Comment by UtechtDustin** [comment]
@wenzhixin the issue and the commit are from 2015.
As this feature is gone for years and nobody complains about it we should decide if this feature makes sense (as it also cause # #5427).
I dont know anybody who use the tabulator to navigate to a table header for sorting.

What do you think @wenzhixin @djhvscf ?

**Comment by djhvscf** [comment]
Well, we can remove that feature but let's add it as a breaking change in our release notes

**Comment by UtechtDustin** [comment]
@djhvscf i don't think we have to note that, as this feature stopped work a long time ago.

**Comment by djhvscf** [comment]
Got it

**Comment by UtechtDustin** [comment]
@wenzhixin still waiting :-)

**Review by wenzhixin — APPROVED** [review]

**Pull request merged**
