### PR TITLE
Release the new extension - multiple-selection-row

### PR DESCRIPTION
**Pull request by djhvscf**
Example: http://jsfiddle.net/djhvscf/e3nk137y/7560/

### CODE REVIEW

**Comment by wenzhixin** [comment]
Great

**Comment by yooceii** [comment]
@djhvscf  I cannot use shift to select another row. The multipleSelectRowLastSelectedRow is undefined.

**Comment by djhvscf** [comment]
@yooceii that is correct, could you open a new issue?

**Comment by yooceii** [comment]
@djhvscf  sure

**Pull request merged**
