### PR TITLE
Fix issue in cookie extension and added triggerSearch method in filterControl extension

### LINKED ISSUE #2427: Do not hit the server again if one request is already on the way.
The user should not be allowed to add any text in the filters when it is waiting for the data from server. For eg. if i search 'a' in a text box and server takes some time to respond and in the meantime if i press any key again, it will again hit once the first request is completed.

JS Fiddle: http://jsfiddle.net/e3nk137y/7118/

### LINKED ISSUE #2443: Any way of manually triggering the filter control search?
I would like to be able to manually trigger the filter-control search upon the click of a button.

i.e. users select all their filters within column headings (via the filter-control extension), and then click a button to trigger the update of the table based on the filter criteria they've selected.

I don't see a way of manually triggering that process... any ideas?

### LINKED ISSUE #2499: Blocked cookies should not throw exception
In chrome in some cases cookies are blocked by default causing bootstrap table to throw an exception:

`Configuration error. Please review the cookieIdTable, cookieExpire properties, if those properties are ok, then this browser does not support the cookies`

### PR DESCRIPTION
**Pull request by djhvscf**
Fix #2499 
Fix #2443 
Fix #2427

### CODE REVIEW

**Comment by wenzhixin** [comment]
👍

**Comment by Junglefish** [comment]
Are there any examples available as to how to use the triggerSearch() method?

**Comment by gl0bix** [comment]
coming to this again, like @Junglefish, I would really appreciate a quick example, on how `triggerSearch()` for example is implementet for a bootstrap-table

**Comment by Maximilian-L** [comment]
Has anyone managed to get this to work? Whenever I triggerSearch(), no filters are applied. An example would be very useful.

**Comment by UtechtDustin** [comment]
@Maximilian-L could you please open an issue for that ?
Please also provide us an example using our [Editor](https://live.bootstrap-table.com/).

**Pull request merged**
