### PR TITLE
Fix filter-control when using & in value

### LINKED ISSUE #5344: Filter Control 'Select' Duplicates Values When Ampersand (&) in Data
**Bootstraptable version(s) affected**:
1.18.0

**Description**  
When table data contains an ampersand (&), the 'select' filter control duplicates values in the list. I haven't noticed this with other special characters.

**Example**  
https://live.bootstrap-table.com/code/valoukh/4929

**Additional context**  
Tested in Firefox, Chromium Edge, Chrome

### PR DESCRIPTION
**Pull request by Moutard3**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5344

**Example(s)?**
Before: https://live.bootstrap-table.com/code/valoukh/4929
After: https://live.bootstrap-table.com/code/Moutard3/5115 (github src `moutard3:fix/5344`)

### CODE REVIEW

**Comment by djhvscf** [comment]
Good, but the search is not working. My question isL is this PR intended to resolved only the dropdown issue? @Moutard3

**Review by djhvscf — CHANGES_REQUESTED** [review]
Good, but the search is not working. My question isL is this PR intended to resolved only the dropdown issue? @Moutard3

**Comment by Moutard3** [comment]
> Good, but the search is not working. My question isL is this PR intended to resolved only the dropdown issue? @Moutard3

Do you have a non-working example? Or steps to reproduce?
This PR is only intended to fix #5344 nothing else.

**Comment by UtechtDustin** [comment]
@Moutard3 use your after example and select `Row 3 & Val 2` from the select.
The row with `Row 3 & Val 2` will be not shown.

**Comment by Moutard3** [comment]
@UtechtDustin @djhvscf The issue did not mention this problem, I sent a correction.

**Review by UtechtDustin — APPROVED** [review]

**Comment by UtechtDustin** [comment]
@djhvscf its fine for me, what do you think ?

**Review by djhvscf — APPROVED** [review]

**Pull request merged**
