### PR TITLE
Table Footer

### PR DESCRIPTION
**Pull request by yonjah**
Made changes to allow adding sticky footer to the table.

I wasn't sure how to change the Docs so here are the main API changes -
global options 
* `showFooter` default `false`

column option
* `falign` _String_ default `undefined` for column text alignment
* `footerFormatter`  _Function_ default `undefined` for showing the footer text
  * `footerFormatter` Will be called with the `column` object as its context and take one parameter
  * param data _Array_ the array of all the rows data
  * return String The text that will be shown in the footer

relevent issues 
[#4](https://github.com/wenzhixin/bootstrap-table/issues/4) 
[#255](https://github.com/wenzhixin/bootstrap-table/issues/255)

### CODE REVIEW

**Comment by djhvscf** [comment]
:+1:

**Comment by yonjah** [comment]
I created an example demo here -
http://jsfiddle.net/L6tm1tt3/

There a few issues / improvements to be added -
* support of `tfoot` (like thead) -
  * will allow easy way to add static strings to footer
  * will not break size if footer value is longer than body value

**Comment by wenzhixin** [comment]
Good job! but I can't automatically merge this pull request. I think you need to `rebase` the repo.

**Comment by yonjah** [comment]
I merged the changes
it should be work now

**Comment by wenzhixin** [comment]
Can you help to update the [docs](https://github.com/wenzhixin/bootstrap-table/tree/master/docs/_i18n/en/documentation)?
* table-options.md
* column-options.md

**Comment by yonjah** [comment]
Sure

**Comment by yonjah** [comment]
Created a new pull request https://github.com/wenzhixin/bootstrap-table/pull/589

we should probably add post-footer event as well.
I'll try to do it when I'll add the `tfoot` integration

**Comment by wenzhixin** [comment]
That sounds great, thanks for your excellent work!

**Pull request merged**
