### PR TITLE
Fixed triggerSearch cannot work bug

### LINKED ISSUE #4604: Enabling 'search: true' in bootstrapTable causes the 'triggerSearch' method to not refresh the search. [1.15.4]
I hope I'm not the only one getting this issue, anyway, here are the steps to reproduce this.

**Steps to reproduce:**

1. Enable 'search: true' in the bootstrapTable initializer.
2. Call `$('#table').bootstrapTable('triggerSearch');`
3. The table no longer refreshes, now if you disable `search: true`, it works just fine, which confuses me.

Thanks in advance.

### PR DESCRIPTION
**Pull request by wenzhixin**
Fix #4604

Before: https://live.bootstrap-table.com/code/wenzhixin/857
After: https://live.bootstrap-table.com/code/wenzhixin/858

Problem: https://stackoverflow.com/questions/39649156/event-currenttarget-changes-after-settimeout

### CODE REVIEW

**Comment by UtechtDustin** [comment]
Im sure we had a issue which removed the currentTarget, because of a other issue...
I will try to search the issue/PR tomorrow!

**Comment by UtechtDustin** [comment]
I cant find the issue..

**Comment by wenzhixin** [comment]
So, can we merge?

**Comment by UtechtDustin** [comment]
I mean we had an issue which is realted to the eventTarget, but i cant find it.    
We can merge it, but it is possible that someone will reopen/comment on the old issue.

**Comment by wenzhixin** [comment]
#4400 ?

**Comment by UtechtDustin** [comment]
yes you found it ! :D
Could you check if the issue #2776, exists with your fix ?

**Comment by wenzhixin** [comment]
Yes @UtechtDustin , fix #2776: https://live.bootstrap-table.com/code/wenzhixin/894

image

image

**Pull request merged**
