### PR TITLE
fixed cookie issue with radiobuttons

### LINKED ISSUE #5095: Cookie extension still does not work with radio button custom filter controls
See this previous issue: [https://github.com/wenzhixin/bootstrap-table/issues/5048](https://github.com/wenzhixin/bootstrap-table/issues/5048)

The cookie extension still doesn't work with custom filter controls if they are radio buttons. The filter is saved and loaded correctly, but the appropriate radio button is not selected:
[https://live.bootstrap-table.com/code/jdhenry08/3446](https://live.bootstrap-table.com/code/jdhenry08/3446)

### PR DESCRIPTION
**Pull request by UtechtDustin**
**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5095

**Example(s)?**
Before: https://live.bootstrap-table.com/code/jdhenry08/3446
After: https://live.bootstrap-table.com/code/UtechtDustin/3465

### CODE REVIEW

**Comment by djhvscf** [comment]
Fix conflicts @UtechtDustin

**Comment by wenzhixin** [comment]
Seems that this bug has been fixed in the develop branch: https://live.bootstrap-table.com/code/jdhenry08/3446 ?

**Comment by UtechtDustin** [comment]
@wenzhixin no its not fixed (my before example use the develop branch btw.).
Peek 2020-06-20 13-03

**Comment by wenzhixin** [comment]
OK, we need to resolve the conflicts.

**Comment by UtechtDustin** [comment]
@wenzhixin which conflicts ?

**Comment by wenzhixin** [comment]
image

You can use:
```
git checkout develop
git pull
git checkout fix/5095
git rebase develop
```

**Comment by UtechtDustin** [comment]
@wenzhixin as i asked there was no conflicts :P
Now there are conflicts after something was merged, i will resolve the conflicts later.

**Pull request merged**
