### PR TITLE
Added checkInvert method, that inverts current selections

### PR DESCRIPTION
**Pull request by Real-Gecko**
Added new method discussed in #1922

### CODE REVIEW

**Comment by djhvscf** [comment]
Please update the documentation

**Comment by Real-Gecko** [comment]
Done.

**Comment by wenzhixin** [comment]
Thanks @Real-Gecko, please help to add an jsfiddle example, and I will add it to #1765.

**Comment by Real-Gecko** [comment]
https://jsfiddle.net/RealGecko/bxwywcx2/

**Comment by djhvscf** [comment]
That script does not work

**Comment by Real-Gecko** [comment]
Sorry, forgot to add `checkInvert` to `allowedMethods`.

Fixed here https://github.com/wenzhixin/bootstrap-table/pull/1945

Updated the fiddle https://jsfiddle.net/RealGecko/bxwywcx2/

**Comment by wenzhixin** [comment]
Updated: https://jsfiddle.net/bxwywcx2/5/

**Comment by Real-Gecko** [comment]
Made your version default for this fiddle.

**Pull request merged**
