### PR TITLE
[wip] webpack support

### LINKED ISSUE #2618: Using the component with webpack
Has anybody managed to bundle this component using webpack? It is on NPM but I have not been able to bundle it and could not find any information.

### PR DESCRIPTION
**Pull request by gpedro**
IIFE is useless, because babeljs does this automatically. this makes able to work with Webpack.

resolves #2618

### CODE REVIEW

**Comment by gpedro** [comment]
ready for merge.

**Comment by wenzhixin** [comment]
We don't need to modify the `dist` folder.

**Comment by gpedro** [comment]
@wenzhixin 
i'll remove my `dist` to avoid conflicts.

about webpack integration, after many tries i found a trick to run without problems.
but i thing this repository should be transform to a team, because some third-party libraries don't have published to npm or is archived/outdated and sometimes require a fix to works great!

**Comment by wenzhixin** [comment]
What problems do you have?

**Comment by wenzhixin** [comment]
Close this PR, if you are working on it please submit a new PR, thanks.

**Pull request closed without merging**
