### PR TITLE
Fix for #2217

### PR DESCRIPTION
**Pull request by kolupaevri**
Qucik fix for #2217.

Looking for `<tfoot>` tag with a single `<tr>` and set footer with it's text (title) or by footerFormatter.

### CODE REVIEW

**Comment by kolupaevri** [comment]
Example: https://jsfiddle.net/2okdmz61/

**Comment by wenzhixin** [comment]
Thanks @kolupaevri, but still has problems: https://github.com/wenzhixin/bootstrap-table/issues/2217#issuecomment-217336914.

**Comment by djhvscf** [comment]
Any update here, @kolupaevri?

**Comment by djhvscf** [comment]
Hi! We don't have any reply in that case we are going to close this PR. If you want, please create a new **PR** with this change against develop.

**Pull request closed without merging**
