### PR TITLE
Improvements for multi-select on filter control rework

### PR DESCRIPTION
**Pull request by albfan**
**Bug fix?**
No

**New Feature?**
Yes

**Resolve an issue?**
relates to #3298 

This fix some things for related PR #5583 

**Example(s)?**

About multi select: https://live.bootstrap-table.com/code/albfan/7745     

Captura de pantalla de 2021-05-14 17-39-04

### CODE REVIEW

**Comment by albfan** [comment]
Added option to avoid adding empty option on multiselect

**Comment by wenzhixin** [comment]
@djhvscf please help to review this PR.

**Comment by djhvscf** [comment]
Reviewing it

**Review by djhvscf — APPROVED** [review]

**Comment by xama** [comment]
Hello, 

I'm trying to add a multiple select on filter column, like in the exemple 
https://live.bootstrap-table.com/code/albfan/7745

But i think this is not working, even in the example;

I added the two attributes on my column :
data-filter-control="select"
data-filter-control-multiple-select="true"


Thanks for help !

**Comment by albfan** [comment]
For whatever reason, that live example didn't work anymore (something related with live editor)

This is the same example saved again:

https://live.bootstrap-table.com/code/albfan/13228

**Comment by xama** [comment]
Thank you for your response albfan

But even the new example not working : https://live.bootstrap-table.com/code/albfan/13228

here is a screen shot of what I get :  
https://user-images.githubusercontent.com/4871623/196887182-912a60d1-9866-4e6f-9d03-539d727dfede.mp4

**Comment by albfan** [comment]
I check again and is related with:

https://raw.githubusercontent.com/albfan/bootstrap-table/feature/multiselect-filtercontrol/src/themes/_theme.scss

it miss:

https://cdn.jsdelivr.net/gh/albfan/bootstrap-table@feature/multiselect-filtercontrol/src/themes/_variables.scss

which is indeed not there

not sure where it comes from

I update again to use https://live.bootstrap-table.com/code/albfan/7745

**Pull request merged**
