### PR TITLE
Provide typings

### PR DESCRIPTION
**Pull request by jregistr**
Provide simple typings to that this library out of the box is ready for typescript. 
There is though a typings out there for this library under the definitelyTyped umbrella,
but it is extremely outdated and isn't correct. For instance, ts compiler will give an error for the line
$('#someId').bootstrapTable('method', {});
This pull requests adds a simple but ready type definition.

### CODE REVIEW

**Comment by jregistr** [comment]
Updated commit to include change to package.json.

**Comment by roddypratt** [comment]
It would be great to have 'full' typescript definitions rather than the simple stubs here.

**Comment by wenzhixin** [comment]
@roddypratt PR is welcome.

**Comment by WoLpH** [comment]
Here's a bunch of definitions I've generated from the constants file with at least the parameters functioning. If anyone has more time than I do to implement it feel free to link it all up :)

```typescript
interface BootstrapTableConstants{
    classes: {buttons: string; buttonsGroup: string; inputGroup: string; buttonsPrefix: string; paginationActive: string; buttonActive: string; dropdownActive: string; pull: string; input: string; dropup: string; buttonsDropdown: string; paginationDropdown: string; inputPrefix: string};
    html: {searchInput: string; searchButton: string; pagination: string[]; pageDropdown: string[]; inputGroup: string; toolbarDropdown: string[]; icon: string; pageDropdownItem: string; paginationItem: string; toolbarDropdownSeparator: string; dropdownCaret: string; searchClearButton: string; toolbarDropdownItem: string};
    iconsPrefix: string;
    icons: {toggleOff: string; clearSearch: string; detailOpen: string; search: string; fullscreen: string; columns: string; detailClose: string; refresh: string; paginationSwitchDown: string; paginationSwitchUp: string; toggleOn: string}
}

interface BootstrapTableEvents{
    'refresh.bs.table': string;
    'load-error.bs.table': string;
    'click-row.bs.table': string;
    'dbl-click-row.bs.table': string;
    'post-body.bs.table': string;
    'collapse-row.bs.table': string;
    'reset-view.bs.table': string;
    'click-cell.bs.table': string;
    'check-all.bs.table': string;
    'post-footer.bs.table': string;
    'uncheck.bs.table': string;
    'check-some.bs.table': string;
    'refresh-options.bs.table': string;
    'pre-body.bs.table': string;
    'uncheck-some.bs.table': string;
    'expand-row.bs.table': string;
    'all.bs.table': string;
    'uncheck-all.bs.table': string;
    'column-switch.bs.table': string;
    'check.bs.table': string;
    'search.bs.table': string;
    'load-success.bs.table': string;
    'dbl-click-cell.bs.table': string;
    'page-change.bs.table': string;
    'post-header.bs.table': string;
    'toggle.bs.table': string;
    'sort.bs.table': string;
    'scroll-body.bs.table': string
}

interface BootstrapTableColumn{
    sortName: undefined;
    widthUnit: string;
    sorter: undefined;
    searchFormatter: boolean;
    titleTooltip: undefined;
    falign: undefined;
    title: undefined;
    align: undefined;
    radio: boolean;
    colspan: undefined;
    showSelectTitle: boolean;
    rowspan: undefined;
    checkbox: boolean;
    halign: undefined;
    switchable: boolean;
    class: undefined;
    escape: boolean;
    events: undefined;
    order: string;
    visible: boolean;
    detailFormatter: undefined;
    valign: undefined;
    sortable: boolean;
    cellStyle: undefined;
    searchable: boolean;
    footerFormatter: undefined;
    formatter: undefined;
    checkboxEnabled: boolean;
    field: undefined;
    width: undefined;
    clickToSelect: boolean;
    searchHighlightFormatter: boolean;
    cardVisible: boolean
}

interface BootstrapTableLocale{
    formatPaginationSwitchDown(): string;

    formatColumns(): string;

    formatAllRows(): string;

    formatLoadingMessage(): string;

    formatSRPaginationPreText(): string;

    formatPaginationSwitch(): string;

    formatDetailPagination(totalRows): string;

    formatNoMatches(): string;

    formatSRPaginationNextText(): string;

    formatSearch(): string;

    formatFullscreen(): string;

    formatShowingRows(pageFrom, pageTo, totalRows, totalNotFiltered): string;

    formatSRPaginationPageText(page): string;

    formatClearSearch(): string;

    formatPaginationSwitchUp(): string;

    formatToggle(): string;

    formatToggleOff(): string;

    formatColumnsToggleAll(): string;

    formatRefresh(): string;

    formatToggleOn(): string;

    formatRecordsPerPage(pageNumber): string
}

interface BootstrapTableOptions{
    onCheck(row): boolean;

    loadingFontSize: string;

    onDblClickCell(field, value, row, $element): boolean;

    rowStyle(row, index): {};

    showColumnsToggleAll: boolean;

    footerStyle(column): {};

    onUncheck(row): boolean;

    pageSize: number;
    footerField: string;
    showFullscreen: boolean;
    sortStable: boolean;
    searchAlign: string;
    ajax: undefined;

    onAll(name, args): boolean;

    onClickRow(item, $element): boolean;

    ajaxOptions: {};

    onCheckSome(rows): boolean;

    customSort: undefined;
    iconSize: undefined;

    onCollapseRow(index, row): boolean;

    searchHighlight: boolean;
    height: undefined;

    onUncheckSome(rows): boolean;

    onToggle(cardView): boolean;

    ignoreClickToSelectOn({tagName}: {tagName: any}): any;

    cache: boolean;
    method: string;

    onColumnSwitch(field, checked): boolean;

    searchSelector: boolean;
    strictSearch: boolean;
    multipleSelectRow: boolean;

    onLoadError(status): boolean;

    buttonsToolbar: undefined;
    paginationVAlign: string;
    showColumnsSearch: boolean;
    queryParamsType: string;
    sortOrder: undefined;
    paginationDetailHAlign: string;
    customSearch: undefined;
    visibleSearch: boolean;
    showButtonText: boolean;
    sortName: undefined;
    columns: any[][];

    onScrollBody(): boolean;

    iconsPrefix: string;

    onPostBody(): boolean;

    search: boolean;
    searchOnEnterKey: boolean;
    searchText: string;

    responseHandler(res): any;

    toolbarAlign: string;
    paginationParts: string[];
    cardView: boolean;
    showSearchButton: boolean;
    escape: boolean;
    searchTimeOut: number;
    buttonsAlign: string;
    buttonsOrder: string[];

    detailFormatter(index, row): string;

    onDblClickRow(item, $element): boolean;

    paginationNextText: string;
    buttonsPrefix: string;

    loadingTemplate(loadingMessage): string;

    theadClasses: string;

    onLoadSuccess(data): boolean;

    url: undefined;
    toolbar: undefined;

    onPostHeader(): boolean;

    sidePagination: string;
    clickToSelect: boolean;
    virtualScrollItemHeight: undefined;

    rowAttributes(row, index): {};

    dataField: string;
    idField: undefined;

    onSort(name, order): boolean;

    pageNumber: number;
    data: any[];
    totalNotFilteredField: string;
    undefinedText: string;

    onSearch(text): boolean;

    onPageChange(number, size): boolean;

    paginationUseIntermediate: boolean;
    searchAccentNeutralise: boolean;
    singleSelect: boolean;
    showButtonIcons: boolean;
    showPaginationSwitch: boolean;

    onPreBody(data): boolean;

    detailFilter(index, row): boolean;

    detailViewByClick: boolean;
    totalField: string;
    contentType: string;
    showColumns: boolean;
    totalNotFiltered: number;
    checkboxHeader: boolean;

    onRefresh(params): boolean;

    dataType: string;
    paginationPreText: string;
    showToggle: boolean;
    detailView: boolean;
    serverSort: boolean;
    totalRows: number;
    silentSort: boolean;

    onPostFooter(): boolean;

    selectItemName: string;
    detailViewIcon: boolean;
    detailViewAlign: string;
    minimumCountColumns: number;
    uniqueId: undefined;

    onResetView(): boolean;

    paginationHAlign: string;
    sortClass: undefined;
    pagination: boolean;

    queryParams(params): any;

    paginationSuccessivelySize: number;
    classes: string;
    rememberOrder: boolean;
    paginationPagesBySide: number;
    trimOnSearch: boolean;
    showRefresh: boolean;
    locale: undefined;

    onCheckAll(rows): boolean;

    showFooter: boolean;

    headerStyle(column): {};

    maintainMetaData: boolean;

    onRefreshOptions(options): boolean;

    showExtendedPagination: boolean;
    smartDisplay: boolean;
    paginationLoop: boolean;
    virtualScroll: boolean;
    sortReset: boolean;
    filterOptions: {filterAlgorithm: string};

    onUncheckAll(rows): boolean;

    showSearchClearButton: boolean;
    buttons: {};
    showHeader: boolean;

    onClickCell(field, value, row, $element): boolean;

    sortable: boolean;
    icons: {toggleOff: string; clearSearch: string; detailOpen: string; search: string; fullscreen: string; columns: string; detailClose: string; refresh: string; paginationSwitchDown: string; paginationSwitchUp: string; toggleOn: string};

    onExpandRow(index, row, $detail): boolean;

    buttonsClass: string;
    pageList: number[]
}

interface JQuery{
    bootstrapTable(options: BootstrapTableOptions): JQuery;

    bootstrapTable(method: string, ...parameters: any[]): JQuery | any;
}
```

**Comment by djhvscf** [comment]
@WoLpH could you create a PR?

**Comment by WoLpH** [comment]
> @WoLpH could you create a PR?

Done: https://github.com/wenzhixin/bootstrap-table/pull/5405

**Pull request closed without merging**
