### PR TITLE
fix/5828

### LINKED ISSUE #5828: The filter-control input is clearing while searching
The filter-control input is clearing while searching and the filter cannot be cleared.

Tried to change table settings but it persists.

screencast

An example of my table configuration:

https://live.bootstrap-table.com/code/matheusilario/8621

This example works perfectly. But in the image you can see that in the application no.

### PR DESCRIPTION
**Pull request by whizzrd**
**🤔Type of Request**
- [x] **Bug fix**
- [ ] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

Fix #5828 

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

filter controls no longer clear on server search

**💡Example(s)?**

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yeezy69** [comment]
With the changes from 5abee4a the search text remains in the input fields, but the select fields are now empty.

**Comment by whizzrd** [comment]
You are right. I think the problem lies in filtercontrol/utils.js @ syncControls

https://github.com/wenzhixin/bootstrap-table/blob/b42124f671e2af685ac440c8d68a1522e1696c80/src/extensions/filter-control/utils.js#L514 <https://github.com/wenzhixin/bootstrap-table/blob/b42124f671e2af685ac440c8d68a1522e1696c80/src/extensions/filter-control/utils.js#L514>

where it bails when height is not set, however it seems that $header is empty so it doesn't find any controls to sync

**Comment by whizzrd** [comment]
> Change [5abee4a](https://github.com/wenzhixin/bootstrap-table/commit/5abee4a5558f66f40c3c121d29c17f723524271d) works for input fields, but the select fields remain empty :(

this should fix that (in my case when using data-filter-data="url:..." on the columns with data-filter-control="select"

**Comment by yeezy69** [comment]
I tried something like you in a4d2918 too, but it didn't work with the cookie extension :(

**Comment by whizzrd** [comment]
> I tried something like you in [a4d2918](https://github.com/wenzhixin/bootstrap-table/commit/a4d2918a324d0ea1484ff14624bc7ca03f7cc662) too, but it didn't work with the cookie extension :(
> (in my case i using data-filter-data="url:...")

That may be a separate issue: for me when enabling the cookie plugin it does initialise the filter controls with the values from "filterControl" cookie. Could you file a separate issue with repro for that please?

**Comment by djhvscf** [comment]
The issue #5828 is fixed in https://github.com/wenzhixin/bootstrap-table/pull/5583

**Comment by whizzrd** [comment]
> The issue #5828 is fixed in #5583

Thanks, that looks like a really nice improvement to filter-control

**Pull request closed without merging**
