### PR TITLE
Updated cookie extension with selectPage Method.

### PR DESCRIPTION
**Pull request by Xandertje**
Updated cookie extension to extend the selectPage Method so that it updates the state save page number cookie.

### CODE REVIEW

**Comment by djhvscf** [comment]
Can you provide an example of this improvement?

**Comment by Xandertje** [comment]
When the selectPage method is called, the pageNumber cookie is not changed. I needed to add this code in order to get it to work.

**Comment by wenzhixin** [comment]
Can we merge this pull request @djhvscf

**Comment by djhvscf** [comment]
Yes, we can. @wenzhixin

**Pull request merged**
