### PR TITLE
Align to the search field

### PR DESCRIPTION
**Pull request by sebastiangehrt**
**Bug fix?**
No

**New Feature?**
Align the jump-to-page field and button to the style of search field and button for a consistent look

**Resolve an issue?**

**Example(s)?**

### CODE REVIEW

**Comment by djhvscf** [comment]
@sebastiangehrt please review and fix the conflicts

**Comment by sebastiangehrt** [comment]
> @sebastiangehrt please review and fix the conflicts

I hope everything fits now

**Comment by wenzhixin** [comment]
I think we should consider other themes.

**Comment by sebastiangehrt** [comment]
> I think we should consider other themes.

@wenzhixin What do you mean exactly? Now it is similar to the search field. It is currently not nice if the fields and icon are implemented or displayed differently. This pull request unifies the appearance of the two fields. The realization is a standard for combination of fields with icon in bootstrap.

**Comment by UtechtDustin** [comment]
@sebastiangehrt what @wenzhixin means is that the bootstrap-table supports multiple css frameworks which should be tested.

**Comment by wenzhixin** [comment]
Fixed this in #5449, thanks.

**Pull request closed without merging**
