### PR TITLE
Restore focus of filter-controls after clone headers

### PR DESCRIPTION
**Pull request by yenyen**
Given the table height is set
When a search with a filter-control is done 
Then the headers are clone and replace 
And the focus of the filter-control is lost

This pull request try to avoid this situation, by restoring the focus after cloning the headers. The result is not perfect, because the focus is lost during a few ms. And, if the page contains multiple tables with same data-field, then it can be the false control who has focus.

### CODE REVIEW

**Comment by wenzhixin** [comment]
Can we add this feature to `filter-control` extension? @yenyen

**Comment by wenzhixin** [comment]
@djhvscf

**Comment by djhvscf** [comment]
I have to double check this change

**Comment by yenyen** [comment]
@wenzhixin No I don't think we can add this to the filter-control extension.
@djhvscf Yes, please. My code is not very good. But, it fixes a big issue because the filter-control extension is useless if the focus is lost after each search. Maybe you can find a better solution to this problem

**Comment by djhvscf** [comment]
Close this PR. See this https://github.com/wenzhixin/bootstrap-table/pull/1370

**Pull request closed without merging**
