### PR TITLE
add save cookie on event:onPageFirst,  onPagePre, onPageNext, onPageLast

### PR DESCRIPTION
**Pull request by tangjn**
click onPageFirst,  onPagePre, onPageNext, onPageLast button. 
the cookie pageNum not change.

### CODE REVIEW

**Comment by djhvscf** [comment]
I think the change is not complete because you are not checking the cookie value in the init method

**Comment by tangjn** [comment]
hi Dennis,
How to init methon. I don't found the init methon at the example http://issues.wenzhixin.net.cn/bootstrap-table/extensions/cookie.html .

And the example http://issues.wenzhixin.net.cn/bootstrap-table/extensions/cookie.html have the same bug.

You can find the bug by step:
1. click the link: http://issues.wenzhixin.net.cn/bootstrap-table/extensions/cookie.html
2. click page 2
3. click first page (not click page1)   (look cookie, the pageNumber cookie not change)
4. refresh the page, then the page still at page 2 ,not at page 1.

**Comment by djhvscf** [comment]
Yes, you're right

**Comment by tangjn** [comment]
hi Dennis, 
I had deleted  blank line.

**Comment by djhvscf** [comment]
@wenzhixin you can merge this PR

**Comment by wenzhixin** [comment]
Merged!

**Pull request merged**
