### PR TITLE
Issue 894: click-cell and dbl-click-cell events

### PR DESCRIPTION
**Pull request by jtrumbull**
Added `onClickCell` and `onDblClickCell` events. 

- `click-cell.bs.table`
- `dbl-click-cell.bs.table`

The new events fire at the same time as `click-row` and `dbl-click-row`, and pass the following parameters:

- `field`: The field name from the subject column
- `value`: The value of the subject `<td>` -taken from the data object.
- `row`: The subject data object
- `$element`: The subject `<td>` (jQuery element)

The suggestion came from [Issue # 894](https://github.com/wenzhixin/bootstrap-table/issues/894).

This is my first pull request with `bootstrap-table`, please give feedback.

### CODE REVIEW

**Comment by djhvscf** [comment]
In my perspective everything looks good! but you need to rebase this PR

**Comment by jtrumbull** [comment]
Sorry not too good with CL Git, but i'm learning. Did I correct the issue?

**Comment by djhvscf** [comment]
Yes!! Thanks! @jtrumbull

**Comment by wenzhixin** [comment]
Thanks @jtrumbull , can you help to add the docs? https://github.com/wenzhixin/bootstrap-table/blob/master/docs/_i18n/en/documentation/events.md

**Comment by jtrumbull** [comment]
@wenzhixin: Docs updated. 

I used a translator for the Spanish docs -may need some interpretation.

**Comment by djhvscf** [comment]
In my side the spanish translation is ok

**Pull request merged**
