### PR TITLE
Impoved Search - Added check for comperations (<,>,<=,=<,>=,=>)

### PR DESCRIPTION
**Pull request by Falseee**
I impoved the search checks so comperations search (<,>,<=,=<,>=,=>) are possible now.
This feature was requested by @ManicPumpkin on Issue #3042.

The following comperations are possible:
```
> value
< value
<= value
=< value
>= value
=> value
value <
value >
value <=
value =<
value >=
value =>
```

JsFiddle Demo: https://jsfiddle.net/s2gpvoqu/

### CODE REVIEW

**Comment by wenzhixin** [comment]
Thanks for your contribution!

It seems that there are problems in [this case](https://jsfiddle.net/wenyi/5847mypf/4/), let's see how to improve it.

**Comment by Falseee** [comment]
I fixed the bug ([working example](https://jsfiddle.net/of1cg4tp/1/)), also i improved the documentation about searching (description of the 3 search types (contains, strict and comparison)).

**Comment by wenzhixin** [comment]
Thanks! Fixed the lint errors: https://github.com/wenzhixin/bootstrap-table/commit/d6b1c78812ae36abf8d78d6d98c29a09e7a41487.

**Comment by Falseee** [comment]
@wenzhixin 
My fault i already fixt hat lint errors, but forgott to push it...sorry!
Can you explain me why all `;` will removed, is there a good reason for that or just to save some memory ?

**Comment by wenzhixin** [comment]
Because other ES6 projects remove `;`, so use the same rules, each line can be one less character :)
Also, refer to some of the more popular projects, they also do not use `;`. 
For examples:
https://github.com/twbs/bootstrap/blob/master/js/src/alert.js
https://github.com/vuejs/vue/blob/dev/src/core/index.js

**Pull request merged**
