### PR TITLE
Add Support for Bootstrap 5

### LINKED ISSUE #5100: Bootstrap 5 support
[Bootstrap 5 alpha](url) was released yesterday which **no longer depends on jQuery**.

I think a Bootstrap 5 GA release is still months (or even longer) away but maybe this issue can track / discuss Bootstrap-Table support for Bootstrap 5.

Another interesting part is [Bootstrap Icons](https://blog.getbootstrap.com/2020/05/21/bootstrap-icons-alpha4/). I'm a long-time FontAwesome user but maybe being able to choose between FA and Bootstrap Icons might be interesting for this project.

### PR DESCRIPTION
**Pull request by UtechtDustin**
**Bug fix?**
no

**New Feature?**
yes

**Resolve an issue?**
Fix #5100

**Example(s)?**
Bootstrap 5 is not avaible on the editor.

* [x] Base table functions
* [x] Accent Neutralise
* [x] Addrbar
* [x] Auto Refresh
* [x] Cookie
* [x] Copy Rows
* [x] Defer Url
* [ ] Editable (Cant work, needs update from the x-editable libary maintainer)
* [x] Export
* [x] Filter Control
* [x] Fixed Columns
* [x] Group By V2
* [x] I18n Enhance
* [x] Key Events
* [x] Mobile
* [x] Multiple Sort
* [x] Page Jump To
* [x] Print
* [x] Reorder Columns
* [x] Reorder Rows
* [x] Resizable
* [x] Sticky Header
* [x] Toolbar
* [x] Treegrid

### CODE REVIEW

**Comment by UtechtDustin** [comment]
@djhvscf Any news? :-)

**Comment by djhvscf** [comment]
So far so good. @wenzhixin any input here?

**Comment by UtechtDustin** [comment]
@wenzhixin reminder

**Comment by wenzhixin** [comment]
I will add examples and check.

**Pull request merged**
