### PR TITLE
Enhancement: Allow User to Reorder Columns

### PR DESCRIPTION
**Pull request by NaughtyMC**
Reorder columns on the fly... Just requires the Sortable Interaction from jQuery UI.

### CODE REVIEW

**Comment by NaughtyMC** [comment]
I am not very familiar with GitHub, so this fork is missing the jQuery UI dependency. However, on an independent project this code runs perfectly.

If someone who knows how to add it to my fork (if that's the best way to do it), I would appreciate your input. Thanks!

**Comment by wenzhixin** [comment]
Because this feature is depended on jQuery UI, so I think it can be added as an extension here: https://github.com/wenzhixin/bootstrap-table/tree/master/src/extensions, like other extensions, do you think so?

**Comment by NaughtyMC** [comment]
Yes, that sounds good to me!

**Comment by wenzhixin** [comment]
Can you help to write an extension like others?

**Comment by NaughtyMC** [comment]
I will work on it when I get the chance

**Pull request closed without merging**
