### PR TITLE
Added titles to the export and filter-control buttons

### PR DESCRIPTION
**Pull request by jermeyjungbeker**
Added titles to the export and filter-control buttons that are displayed on the top of a table.

### CODE REVIEW

**Comment by djhvscf** [comment]
@jermeyjungbeker you have to do the Pull Request against "develop" branch

**Comment by jermeyjungbeker** [comment]
Oke that was stupid from me. Will do.

**Comment by jermeyjungbeker** [comment]
#1709 made a new one to develop. Will close this because it has no use anymore

**Comment by djhvscf** [comment]
Thanks @jermeyjungbeker

**Pull request closed without merging**
